//
// v2-simplified-flow routes
// Generated by Cursor
//

const BASE = '/v2-simplified-flow'

module.exports = (router) => {
  router.get(`${BASE}/start`, (req, res) => {
    res.render('v2-simplified-flow/start')
  })
}
