//
// v2-post-baseline routes
// Generated by Cursor
//

const BASE = '/v2-post-baseline'
const notifications = require('../../data/notifications')

const FILTER_KEYS = ['filterKeyword', 'filterCommodity', 'filterOrigin', 'filterConsignee', 'filterDestination', 'filterStatus', 'filterStartDate', 'filterEndDate', 'filterPeriod']

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

function parseArrivalDate (str) {
  if (!str || typeof str !== 'string') return null
  const match = str.match(/^(\d{1,2})\s+(\w+)\s+(\d{4})$/)
  if (!match) return null
  const monthIndex = MONTHS.findIndex(m => m.toLowerCase() === match[2].toLowerCase())
  if (monthIndex < 0) return null
  return new Date(parseInt(match[3], 10), monthIndex, parseInt(match[1], 10)).getTime()
}

// Build species-to-code map for normalising commodity display
function getSpeciesToCodeMap () {
  const commoditiesData = require('../../data/commodities.js')
  const map = {}
  for (const [key, details] of Object.entries(commoditiesData)) {
    if (details.code && details.species) {
      details.species.forEach(s => { map[s] = details.code })
    }
  }
  return map
}

function normaliseCommodityDisplay (commodity, speciesToCode) {
  if (!commodity || typeof commodity !== 'string') return commodity || ''
  if (/\(\d+\)$/.test(commodity.trim())) return commodity
  const code = speciesToCode[commodity.trim()]
  return code ? `${commodity} (${code})` : commodity
}

function sortNotifications (list, sortOption) {
  const sorted = [...list]
  const byArrival = (a, b) => {
    const ta = parseArrivalDate(a.arrival) || 0
    const tb = parseArrivalDate(b.arrival) || 0
    return ta - tb
  }
  if (sortOption === 'arrival-desc') {
    sorted.sort((a, b) => byArrival(b, a))
  } else if (sortOption === 'arrival-asc') {
    sorted.sort(byArrival)
  } else if (sortOption === 'reference') {
    sorted.sort((a, b) => String(a.reference || '').localeCompare(b.reference || ''))
  }
  return sorted
}

function filterNotifications (filterData, sourceList) {
  const list = sourceList || notifications
  const str = (v) => (v == null ? '' : String(v))
  return list.filter(n => {
    const keyword = (filterData.keyword || '').trim().toLowerCase()
    if (keyword) {
      const search = `${str(n.reference)} ${str(n.commodity)} ${str(n.origin)} ${str(n.consignee)} ${str(n.consignor)}`.toLowerCase()
      if (!search.includes(keyword)) return false
    }

    const commodity = (filterData.commodity || '').trim().toLowerCase()
    if (commodity && !str(n.commodity).toLowerCase().includes(commodity)) return false

    const origin = (filterData.origin || '').trim().toLowerCase()
    if (origin && !str(n.origin).toLowerCase().includes(origin)) return false

    const consignee = (filterData.consignee || '').trim().toLowerCase()
    if (consignee) {
      const match = str(n.consignee).toLowerCase().includes(consignee) || str(n.consignor).toLowerCase().includes(consignee)
      if (!match) return false
    }

    const status = (filterData.status || '').trim().toLowerCase()
    if (status && n.status !== status) return false

    return true
  })
}

module.exports = (router) => {
  router.get(`${BASE}/start`, (req, res) => {
    res.render('v2-post-baseline/start')
  })

  router.get(`${BASE}/dashboard`, (req, res) => {
    const data = req.session.data || {}
    FILTER_KEYS.forEach(key => {
      if (req.query[key] !== undefined) data[key] = req.query[key]
    })
    if (req.query.sort !== undefined) data.sort = req.query.sort
    const toYYYYMMDD = (d) => `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
    const today = new Date()
    const defaultStart = toYYYYMMDD(new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000))
    const defaultEnd = toYYYYMMDD(today)
    if (data.filterPeriod) {
      const d = new Date(today)
      if (data.filterPeriod === 'last-1-hour') {
        data.filterStartDate = defaultEnd
        data.filterEndDate = defaultEnd
      } else if (data.filterPeriod === 'last-24-hours') {
        d.setDate(d.getDate() - 1)
        data.filterStartDate = toYYYYMMDD(d)
        data.filterEndDate = defaultEnd
      } else if (data.filterPeriod === 'last-7-days') {
        d.setDate(d.getDate() - 7)
        data.filterStartDate = toYYYYMMDD(d)
        data.filterEndDate = defaultEnd
      } else if (data.filterPeriod === 'last-30-days') {
        d.setDate(d.getDate() - 30)
        data.filterStartDate = toYYYYMMDD(d)
        data.filterEndDate = defaultEnd
      }
    }
    if (!data.filterStartDate) data.filterStartDate = defaultStart
    if (!data.filterEndDate) data.filterEndDate = defaultEnd
    const filterData = {
      keyword: data.filterKeyword,
      commodity: data.filterCommodity,
      origin: data.filterOrigin,
      consignee: data.filterConsignee,
      destination: data.filterDestination,
      status: data.filterStatus,
      startDate: data.filterStartDate,
      endDate: data.filterEndDate
    }
    const submitted = data.submittedNotifications || []
    const allNotifications = [...notifications, ...submitted]
    const filtered = filterNotifications(filterData, allNotifications)
    const sortOption = data.sort || 'arrival-desc'
    const sorted = sortNotifications(filtered, sortOption)
    const speciesToCode = getSpeciesToCodeMap()
    const normalised = sorted.map(n => ({
      ...n,
      commodity: normaliseCommodityDisplay(n.commodity, speciesToCode)
    }))

    const perPage = 20
    const page = Math.max(1, parseInt(req.query.page, 10) || 1)
    const total = normalised.length
    const totalPages = Math.max(1, Math.ceil(total / perPage))
    const pageNum = Math.min(page, totalPages)
    const start = (pageNum - 1) * perPage
    const paginated = normalised.slice(start, start + perPage)

    req.session.data.resultsCount = total
    res.locals.notifications = paginated
    res.locals.dashboardPage = pageNum
    res.locals.dashboardTotalPages = totalPages
    const allParams = [...FILTER_KEYS, 'sort']
      .filter(k => data[k] != null && data[k] !== '')
      .map(k => `${encodeURIComponent(k)}=${encodeURIComponent(data[k])}`)
    res.locals.dashboardQueryParams = allParams.join('&')
    const filterParamKeys = ['filterKeyword', 'filterCommodity', 'filterOrigin', 'filterConsignee', 'filterDestination', 'filterStatus']
    res.locals.filterQueryBase = filterParamKeys
      .filter(k => data[k])
      .map(k => `${encodeURIComponent(k)}=${encodeURIComponent(data[k])}`)
      .join('&')

    const euCountries = require('../../data/eu-countries.js')
    const originsFromData = [...new Set(allNotifications.map(n => n.origin).filter(Boolean))]
    res.locals.originCountries = [...new Set([...euCountries, ...originsFromData])].sort()

    const isDefaultDateRange = (data.filterStartDate === defaultStart && data.filterEndDate === defaultEnd) || (!data.filterPeriod && !data.filterStartDate && !data.filterEndDate)
    const activeFilters = []
    const buildClearUrl = (...excludeKeys) => {
      const excludeSet = new Set(excludeKeys)
      const params = [...FILTER_KEYS, 'sort']
        .filter(k => !excludeSet.has(k) && data[k] != null && data[k] !== '')
        .map(k => `${encodeURIComponent(k)}=${encodeURIComponent(data[k])}`)
      return `${BASE}/dashboard${params.length ? '?' + params.join('&') : ''}`
    }
    if ((data.filterKeyword || '').trim()) {
      activeFilters.push({ label: 'Keyword: ' + data.filterKeyword.trim(), clearHref: buildClearUrl('filterKeyword') })
    }
    if ((data.filterCommodity || '').trim()) {
      activeFilters.push({ label: 'Commodity: ' + data.filterCommodity.trim(), clearHref: buildClearUrl('filterCommodity') })
    }
    if ((data.filterOrigin || '').trim()) {
      activeFilters.push({ label: 'Country of origin: ' + data.filterOrigin.trim(), clearHref: buildClearUrl('filterOrigin') })
    }
    if ((data.filterConsignee || '').trim()) {
      activeFilters.push({ label: 'Consignee / Consignor: ' + data.filterConsignee.trim(), clearHref: buildClearUrl('filterConsignee') })
    }
    if ((data.filterDestination || '').trim()) {
      activeFilters.push({ label: 'Place of destination: ' + data.filterDestination.trim(), clearHref: buildClearUrl('filterDestination') })
    }
    if (data.filterStatus && data.filterStatus !== '') {
      activeFilters.push({ label: 'Status: ' + (data.filterStatus === 'draft' ? 'Draft' : 'Submitted'), clearHref: buildClearUrl('filterStatus') })
    }
    if (!isDefaultDateRange && (data.filterPeriod || data.filterStartDate || data.filterEndDate)) {
      const periodLabels = { 'last-1-hour': 'Last 1 hour', 'last-24-hours': 'Last 24 hours', 'last-7-days': 'Last 7 days', 'last-30-days': 'Last 30 days' }
      const dateLabel = data.filterPeriod ? (periodLabels[data.filterPeriod] || 'Custom date range') : 'Custom date range'
      activeFilters.push({ label: 'Date range: ' + dateLabel, clearHref: buildClearUrl('filterPeriod', 'filterStartDate', 'filterEndDate') })
    }
    res.locals.activeFilters = activeFilters

    res.render('v2-post-baseline/dashboard')
  })

  router.get(`${BASE}/create/import-type`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    res.render('v2-post-baseline/create/import-type')
  })

  router.post(`${BASE}/create/import-type`, (req, res) => {
    const importType = req.session.data.importType
    if (!importType || importType.trim() === '') {
      req.session.data.errors = { importType: 'Select what you are importing' }
      req.session.data.errorList = [{ href: '#import-type-1', text: 'Select what you are importing' }]
      return res.redirect(`${BASE}/create/import-type`)
    }
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/origin`)
  })

  router.get(`${BASE}/create/import-type-prefill`, (req, res) => {
    req.session.data.importType = 'live-animals'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/origin`)
  })

  router.get(`${BASE}/create/origin`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const euCountries = require('../../data/eu-countries.js')
    const euCountryCodes = require('../../data/eu-country-codes.js')
    res.render('v2-post-baseline/create/origin', {
      euCountries,
      euCountryCodes
    })
  })

  router.post(`${BASE}/create/origin`, (req, res) => {
    const countryOfOrigin = req.session.data.countryOfOrigin
    const regionOfOriginRequired = req.session.data.regionOfOriginRequired
    const errors = {}
    const errorList = []

    if (!countryOfOrigin || countryOfOrigin.trim() === '') {
      errors.countryOfOrigin = 'Select a country'
      errorList.push({ href: '#countryOfOrigin', text: 'Select a country' })
    }
    if (!regionOfOriginRequired || regionOfOriginRequired.trim() === '') {
      errors.regionOfOriginRequired = 'Select if the consignment requires a region of origin code'
      errorList.push({ href: '#region-of-origin-1', text: 'Select if the consignment requires a region of origin code' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/origin`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity`)
  })

  router.get(`${BASE}/create/origin-prefill`, (req, res) => {
    req.session.data.countryOfOrigin = 'France'
    req.session.data.regionOfOriginRequired = 'no'
    req.session.data.consignmentReference = 'REF-2025-001'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity`)
  })

  router.get(`${BASE}/create/commodity`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodities = require('../../data/commodity-list.js')
    res.render('v2-post-baseline/create/commodity', {
      commodities
    })
  })

  router.post(`${BASE}/create/commodity`, (req, res) => {
    const commodity = req.session.data.commodity
    const errors = {}
    const errorList = []

    if (!commodity || commodity.trim() === '') {
      errors.commodity = 'Select a commodity'
      errorList.push({ href: '#commodity', text: 'Select a commodity' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/commodity`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity-species`)
  })

  router.get(`${BASE}/create/commodity-prefill`, (req, res) => {
    req.session.data.commodity = 'Cow'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity-species`)
  })

  router.get(`${BASE}/create/commodity-species`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodity = req.session.data.commodity
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails) {
      return res.redirect(`${BASE}/create/commodity`)
    }

    const commodityTypeItems = commodityDetails.commodityTypes.map(t => ({
      value: t.toLowerCase(),
      text: t
    }))
    const selectedSpecies = req.session.data.commoditySpecies || []
    const speciesItems = commodityDetails.species.map(s => ({
      value: s,
      text: s,
      checked: selectedSpecies.indexOf(s) !== -1
    }))

    res.render('v2-post-baseline/create/commodity-species', {
      commodityDetails,
      commodityTypeItems,
      speciesItems
    })
  })

  router.post(`${BASE}/create/commodity-species`, (req, res) => {
    const species = req.session.data.commoditySpecies
    const errors = {}
    const errorList = []

    if (!species || !Array.isArray(species) || species.length === 0) {
      errors.commoditySpecies = 'Select at least one species'
      errorList.push({ href: '#commoditySpecies-1', text: 'Select at least one species' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/import-reason`)
  })

  router.get(`${BASE}/create/commodity-species-prefill`, (req, res) => {
    const commodityDetails = req.session.data.commodity ? require('../../data/commodities.js')[req.session.data.commodity] : null
    // Use Bos taurus (domestic cattle) for Cow; otherwise first species in list
    const species = commodityDetails && req.session.data.commodity === 'Cow'
      ? 'Bos taurus'
      : (commodityDetails ? commodityDetails.species[0] : 'Bos taurus')
    req.session.data.commoditySpecies = [species]
    req.session.data.commodityType = 'domestic'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/import-reason`)
  })

  router.get(`${BASE}/create/import-reason`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commoditySpecies = req.session.data.commoditySpecies || []
    const horseSpecies = require('../../data/commodity-list.js').horseSpecies
    const showTemporaryAdmissionHorses = commoditySpecies.some(s => horseSpecies.includes(s))
    const internalMarketPurposes = require('../../data/internal-market-purposes.js')

    const purposeItems = internalMarketPurposes.map(p => ({
      value: p.value,
      text: p.text,
      hint: p.hint ? { text: p.hint } : undefined,
      checked: req.session.data.internalMarketPurpose === p.value
    }))

    const escapeHtml = (s) => String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')

    const purposeError = req.session.data.errors && req.session.data.errors.internalMarketPurpose
    const purposeConditionalHtml = `
      <div class="govuk-form-group govuk-!-margin-top-3 ${purposeError ? 'govuk-form-group--error' : ''}">
        <fieldset class="govuk-fieldset" ${purposeError ? 'aria-describedby="internal-market-purpose-error"' : ''}>
          <legend class="govuk-fieldset__legend govuk-fieldset__legend--s">
            Purpose in the internal market
          </legend>
          ${purposeError ? `<p id="internal-market-purpose-error" class="govuk-error-message"><span class="govuk-visually-hidden">Error:</span> ${escapeHtml(purposeError)}</p>` : ''}
          <div class="govuk-radios govuk-radios--small" data-module="govuk-radios">
            ${purposeItems.map((item, i) => `
              <div class="govuk-radios__item">
                <input class="govuk-radios__input" id="internal-market-purpose-${i}" name="internalMarketPurpose" type="radio" value="${escapeHtml(item.value)}" ${item.checked ? 'checked' : ''}>
                <label class="govuk-label govuk-radios__label" for="internal-market-purpose-${i}">${escapeHtml(item.text)}</label>
                ${item.hint ? `<div class="govuk-hint govuk-radios__hint">${escapeHtml(item.hint.text)}</div>` : ''}
              </div>
            `).join('')}
          </div>
        </fieldset>
      </div>
    `

    const importReasonItems = [
      {
        value: 'internal-market',
        text: 'Internal market',
        hint: { text: 'The consignment is intended for sale or use in Great Britain (England, Scotland or Wales).' },
        conditional: { html: purposeConditionalHtml }
      },
      {
        value: 're-entry',
        text: 'Re-entry',
        hint: { text: 'The consignment is authorised for re-entry or includes rejected exports that are re-entering Great Britain.' }
      }
    ]
    if (showTemporaryAdmissionHorses) {
      importReasonItems.push({
        value: 'temporary-admission-horses',
        text: 'Temporary admission horses',
        hint: { text: 'For horses authorised for temporary entry.' }
      })
    }

    res.render('v2-post-baseline/create/import-reason', {
      importReasonItems
    })
  })

  router.post(`${BASE}/create/import-reason`, (req, res) => {
    const importReason = req.session.data.importReason
    const internalMarketPurpose = req.session.data.internalMarketPurpose
    const commoditySpecies = req.session.data.commoditySpecies || []
    const horseSpecies = require('../../data/commodity-list.js').horseSpecies
    const showTemporaryAdmissionHorses = commoditySpecies.some(s => horseSpecies.includes(s))
    const errors = {}
    const errorList = []

    if (!importReason || importReason.trim() === '') {
      errors.importReason = 'Select the main reason for importing the animals'
      errorList.push({ href: '#import-reason-1', text: 'Select the main reason for importing the animals' })
    } else if (importReason === 'temporary-admission-horses' && !showTemporaryAdmissionHorses) {
      errors.importReason = 'Temporary admission horses is only available when importing horses'
      errorList.push({ href: '#import-reason-1', text: 'Select a valid reason for importing the animals' })
    } else if (importReason === 'internal-market' && (!internalMarketPurpose || internalMarketPurpose.trim() === '')) {
      errors.internalMarketPurpose = 'Select the purpose in the internal market'
      errorList.push({ href: '#internal-market-purpose-0', text: 'Select the purpose in the internal market' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/import-reason`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity-quantities`)
  })

  router.get(`${BASE}/create/import-reason-prefill`, (req, res) => {
    req.session.data.importReason = 'internal-market'
    req.session.data.internalMarketPurpose = 'breeding'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity-quantities`)
  })

  router.get(`${BASE}/create/commodity-quantities`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commodityType = req.session.data.commodityType || 'domestic'
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const typeLabel = commodityType === 'game' ? 'Game' : 'Domestic'
    const speciesRows = commoditySpecies.map(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      return {
        key,
        speciesAndType: `${s}, ${typeLabel}`,
        quantityKey: `quantity_${key}`,
        packagesKey: `packages_${key}`
      }
    })

    let totalAnimals = 0
    let totalPackages = 0
    speciesRows.forEach(s => {
      const qty = parseInt(req.session.data[s.quantityKey], 10)
      const pkg = parseInt(req.session.data[s.packagesKey], 10)
      totalAnimals += (isNaN(qty) ? 0 : qty)
      totalPackages += (isNaN(pkg) ? 0 : pkg)
    })

    res.render('v2-post-baseline/create/commodity-quantities', {
      commodityDetails,
      speciesRows,
      totalAnimals,
      totalPackages
    })
  })

  router.post(`${BASE}/create/commodity-quantities`, (req, res) => {
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null
    const errors = {}
    const errorList = []

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const typeLabel = req.session.data.commodityType === 'game' ? 'Game' : 'Domestic'
    const speciesRows = commoditySpecies.map(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      return {
        key,
        speciesAndType: `${s}, ${typeLabel}`,
        quantityKey: `quantity_${key}`,
        packagesKey: `packages_${key}`
      }
    })

    speciesRows.forEach((s, i) => {
      const qtyVal = req.session.data[s.quantityKey]
      if (!qtyVal || String(qtyVal).trim() === '' || parseInt(qtyVal, 10) < 0) {
        errors[s.quantityKey] = 'Enter the number of animals'
        errorList.push({ href: `#quantity-${s.key}`, text: `Enter the number of animals for ${s.speciesAndType}` })
      }
      const pkgVal = req.session.data[s.packagesKey]
      if (pkgVal === undefined || pkgVal === null || String(pkgVal).trim() === '' || parseInt(pkgVal, 10) < 0) {
        errors[s.packagesKey] = 'Enter the number of packages'
        errorList.push({ href: `#packages-${s.key}`, text: `Enter the number of packages for ${s.speciesAndType}` })
      }
    })

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/commodity-quantities`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/animal-identification`)
  })

  router.get(`${BASE}/create/commodity-quantities-prefill`, (req, res) => {
    const commoditySpecies = req.session.data.commoditySpecies || []
    commoditySpecies.forEach(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      req.session.data[`quantity_${key}`] = 2
      req.session.data[`packages_${key}`] = 1
    })
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/animal-identification-prefill`)
  })

  router.get(`${BASE}/create/animal-identification`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commodityType = req.session.data.commodityType || 'domestic'
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const quantityKey = (s) => `quantity_${s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')}`
    const hasQuantities = commoditySpecies.some(s => {
      const q = parseInt(req.session.data[quantityKey(s)], 10)
      return !isNaN(q) && q > 0
    })
    if (!hasQuantities) {
      return res.redirect(`${BASE}/create/commodity-quantities`)
    }

    const typeLabel = commodityType === 'game' ? 'Game' : 'Domestic'
    const speciesRows = commoditySpecies.map(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      const quantityKey = `quantity_${key}`
      const quantity = parseInt(req.session.data[quantityKey], 10) || 0
      const animals = []
      for (let i = 1; i <= quantity; i++) {
        animals.push({
          index: i,
          earTagKey: `earTag_${key}_${i}`,
          passportKey: `passport_${key}_${i}`
        })
      }
      return {
        key,
        speciesAndType: `${s}, ${typeLabel}`,
        quantity,
        animals
      }
    })

    res.render('v2-post-baseline/create/animal-identification', {
      commodityDetails,
      speciesRows
    })
  })

  router.get(`${BASE}/create/animal-identification-prefill`, (req, res) => {
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commodityType = req.session.data.commodityType || 'domestic'
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const quantityKey = (s) => `quantity_${s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')}`
    const hasQuantities = commoditySpecies.some(s => {
      const q = parseInt(req.session.data[quantityKey(s)], 10)
      return !isNaN(q) && q > 0
    })
    if (!hasQuantities) {
      return res.redirect(`${BASE}/create/commodity-quantities`)
    }

    // BCMS (Cattle Tracing System) format: 12-digit ear tag (6 herd + 6 individual), passport UK herd check sequential
    const HERD_MARK = '123456'
    const CHECK_DIGIT = '7'
    let animalCounter = 0
    const isCattle = commodity === 'Cow'
    commoditySpecies.forEach(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      const quantityKey = `quantity_${key}`
      const quantity = parseInt(req.session.data[quantityKey], 10) || 0
      for (let i = 1; i <= quantity; i++) {
        animalCounter++
        if (isCattle) {
          req.session.data[`earTag_${key}_${i}`] = `${HERD_MARK}${String(animalCounter).padStart(6, '0')}`
          req.session.data[`passport_${key}_${i}`] = `UK ${HERD_MARK} ${CHECK_DIGIT} ${String(animalCounter).padStart(5, '0')}`
        } else {
          req.session.data[`earTag_${key}_${i}`] = `PRE-${key}-${i}`
          req.session.data[`passport_${key}_${i}`] = `PASSPORT-${key}-${i}`
        }
      }
    })

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/additional-animal-details`)
  })

  router.get(`${BASE}/create/additional-animal-details`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const quantityKey = (s) => `quantity_${s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')}`
    const hasQuantities = commoditySpecies.some(s => {
      const q = parseInt(req.session.data[quantityKey(s)], 10)
      return !isNaN(q) && q > 0
    })
    if (!hasQuantities) {
      return res.redirect(`${BASE}/create/commodity-quantities`)
    }

    res.render('v2-post-baseline/create/additional-animal-details')
  })

  router.post(`${BASE}/create/additional-animal-details`, (req, res) => {
    const animalsCertifiedFor = req.session.data.animalsCertifiedFor
    const unweanedAnimals = req.session.data.unweanedAnimals
    const errors = {}
    const errorList = []

    if (!animalsCertifiedFor || animalsCertifiedFor.trim() === '') {
      errors.animalsCertifiedFor = 'Select what the animals are certified for'
      errorList.push({ href: '#animals-certified-for-1', text: 'Select what the animals are certified for' })
    }
    if (!unweanedAnimals || unweanedAnimals.trim() === '') {
      errors.unweanedAnimals = 'Select if the consignment contains unweaned animals'
      errorList.push({ href: '#unweaned-animals-1', text: 'Select if the consignment contains unweaned animals' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/additional-animal-details`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/accompanying-documents`)
  })

  router.get(`${BASE}/create/additional-animal-details-prefill`, (req, res) => {
    req.session.data.animalsCertifiedFor = 'breeding-production'
    req.session.data.unweanedAnimals = 'no'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/accompanying-documents`)
  })

  router.get(`${BASE}/create/accompanying-documents`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const documentTypes = require('../../data/document-types.js')
    const documentTypeItems = [{ value: '', text: 'Select document type' }].concat(documentTypes)
    const sessionDocuments = req.session.data.documents
    let documents = (sessionDocuments && sessionDocuments.length) ? sessionDocuments : [{ type: '', reference: '', date: '' }]
    // Normalise date: convert legacy dateDay/dateMonth/dateYear to YYYY-MM-DD for input type="date"
    documents = documents.map(doc => {
      const d = doc || {}
      if (d.date) return { ...d, date: d.date }
      if (d.dateDay && d.dateMonth && d.dateYear) {
        const y = String(d.dateYear).padStart(4, '0')
        const m = String(d.dateMonth).padStart(2, '0')
        const day = String(d.dateDay).padStart(2, '0')
        return { ...d, date: `${y}-${m}-${day}` }
      }
      return { ...d, date: d.date || '' }
    })
    res.render('v2-post-baseline/create/accompanying-documents', {
      documentTypeItems,
      documents
    })
  })

  router.post(`${BASE}/create/accompanying-documents`, (req, res) => {
    const data = req.session.data
    const documents = []
    const errors = {}
    const errorList = []
    let i = 0
    while (data[`documentType_${i}`] !== undefined) {
      const type = data[`documentType_${i}`]
      const reference = (data[`documentReference_${i}`] || '').trim()
      const date = (data[`documentDate_${i}`] || '').trim()
      const filenamesStr = data[`documentAttachmentFilenames_${i}`] || ''
      const attachments = filenamesStr ? filenamesStr.split(',').map(s => s.trim()).filter(Boolean) : []

      if (!type || type.trim() === '') {
        errors[`documentType_${i}`] = 'Select a document type'
        errorList.push({ href: `#document-type-${i}`, text: `Document ${i + 1}: Select a document type` })
      }
      if (reference === '') {
        errors[`documentReference_${i}`] = 'Enter the document reference'
        errorList.push({ href: `#document-reference-${i}`, text: `Document ${i + 1}: Enter the document reference` })
      }
      if (date === '') {
        errors[`documentDate_${i}`] = 'Enter the date of issue'
        errorList.push({ href: `#document-date-${i}`, text: `Document ${i + 1}: Enter the date of issue` })
      }

      documents.push({
        type: type || '',
        reference: reference,
        date: date,
        attachments
      })
      i++
    }
    if (documents.length === 0) {
      documents.push({ type: '', reference: '', date: '', attachments: [] })
    }
    data.documents = documents

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/accompanying-documents`)
    }

    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/addresses`)
  })

  router.get(`${BASE}/create/addresses`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList

    // Store selected consignor when coming from address-consignor-search
    const consignorId = req.query.consignor
    if (req.query.removeConsignor === '1') {
      delete data.consignorId
      delete data.consignorName
      delete data.consignorAddress
      delete data.consignorCountry
      delete data.consignor
    } else if (consignorId) {
      const consignors = require('../../data/consignors.js')
      const selected = consignors.find(c => String(c.id) === String(consignorId))
      if (selected) {
        data.consignorId = selected.id
        data.consignorName = selected.name
        data.consignorAddress = selected.address
        data.consignorCountry = selected.country
        data.consignor = selected
      }
    }

    // Store selected consignee when coming from address-consignee-search
    const consigneeId = req.query.consignee
    if (req.query.removeConsignee === '1') {
      delete data.consigneeId
      delete data.consigneeName
      delete data.consigneeAddress
      delete data.consigneeCountry
      delete data.consigneeAddressLine1
      delete data.consigneeAddressLine2
      delete data.consigneeTown
      delete data.consigneePostcode
      delete data.importerName
      delete data.importerAddress
      delete data.importerCountry
    } else if (consigneeId) {
      const consignees = require('../../data/consignees.js')
      const selectedConsignee = consignees.find(c => String(c.id) === String(consigneeId))
      if (selectedConsignee) {
        data.consigneeId = selectedConsignee.id
        data.consigneeName = selectedConsignee.name
        data.consigneeAddress = selectedConsignee.address
        data.consigneeCountry = selectedConsignee.country
      }
    }

    // Store selected importer when coming from address-consignee-search?for=importer
    const importerId = req.query.importer
    if (importerId) {
      const consignees = require('../../data/consignees.js')
      const selectedImporter = consignees.find(c => String(c.id) === String(importerId))
      if (selectedImporter) {
        data.importerId = selectedImporter.id
        data.importerName = selectedImporter.name
        data.importerAddress = selectedImporter.address
        data.importerCountry = selectedImporter.country
      }
    }

    // Pass consignor explicitly (session may not persist nested objects reliably)
    const selected = data.consignor || (data.consignorName && { name: data.consignorName, address: data.consignorAddress, country: data.consignorCountry })
    const consignorName = (selected && selected.name) || data.consignorName || ''
    const consignorAddress = (selected && selected.address) || data.consignorAddress || ''
    const consignorCountry = (selected && selected.country) || data.consignorCountry || ''
    const hasConsignor = !!(selected || data.consignorId)

    // Handle "Same as consignee" for importer
    if (req.query.importerSameAsConsignee === '1') {
      const hasConsigneeCheck = !!(data.consigneeId && data.consigneeName && data.consigneeAddress && data.consigneeCountry) ||
        !!(data.consigneeName && data.consigneeAddressLine1 && data.consigneeTown && data.consigneePostcode)
      if (hasConsigneeCheck) {
        data.importerId = data.consigneeId
        data.importerName = data.consigneeName
        data.importerAddress = data.consigneeAddress
        data.importerCountry = data.consigneeCountry
        data.importerAddressLine1 = data.consigneeAddressLine1
        data.importerAddressLine2 = data.consigneeAddressLine2
        data.importerTown = data.consigneeTown
        data.importerPostcode = data.consigneePostcode
      }
    }
    if (req.query.removeImporter === '1') {
      delete data.importerId
      delete data.importerName
      delete data.importerAddress
      delete data.importerCountry
      delete data.importerAddressLine1
      delete data.importerAddressLine2
      delete data.importerTown
      delete data.importerPostcode
    }

    // Consignee – build display (from search selection or manual form)
    const hasConsigneeFromSearch = !!(data.consigneeId && data.consigneeName && data.consigneeAddress && data.consigneeCountry)
    const hasConsigneeFromForm = !!(data.consigneeName && data.consigneeAddressLine1 && data.consigneeTown && data.consigneePostcode)
    const hasConsignee = hasConsigneeFromSearch || hasConsigneeFromForm
    const consigneeAddressLines = []
    if (hasConsigneeFromSearch) {
      consigneeAddressLines.push(data.consigneeName, data.consigneeAddress, data.consigneeCountry)
    } else if (hasConsigneeFromForm) {
      if (data.consigneeName) consigneeAddressLines.push(data.consigneeName)
      if (data.consigneeAddressLine1) consigneeAddressLines.push(data.consigneeAddressLine1)
      if (data.consigneeAddressLine2) consigneeAddressLines.push(data.consigneeAddressLine2)
      if (data.consigneeTown) consigneeAddressLines.push(data.consigneeTown)
      if (data.consigneePostcode) consigneeAddressLines.push(data.consigneePostcode + ' United Kingdom')
    }

    // Importer – build display (from same-as-consignee, search, or manual form)
    const hasImporterFromConsignee = !!(data.importerName && (data.importerAddress || data.importerAddressLine1))
    const hasImporter = hasImporterFromConsignee

    // Same as consignee: show when importer is empty OR importer differs from consignee
    const importerMatchesConsignee = hasConsignee && hasImporter && (
      (data.importerId && data.consigneeId && String(data.importerId) === String(data.consigneeId)) ||
      (data.importerName === data.consigneeName && data.importerAddress === data.consigneeAddress) ||
      (data.importerName === data.consigneeName && data.importerAddressLine1 === data.consigneeAddressLine1 && data.importerTown === data.consigneeTown)
    )
    const showSameAsConsignee = hasConsignee && !importerMatchesConsignee
    const importerAddressLines = []
    if (hasImporter) {
      if (data.importerAddress) {
        importerAddressLines.push(data.importerName, data.importerAddress, data.importerCountry || 'United Kingdom')
      } else {
        if (data.importerName) importerAddressLines.push(data.importerName)
        if (data.importerAddressLine1) importerAddressLines.push(data.importerAddressLine1)
        if (data.importerAddressLine2) importerAddressLines.push(data.importerAddressLine2)
        if (data.importerTown) importerAddressLines.push(data.importerTown)
        if (data.importerPostcode) importerAddressLines.push(data.importerPostcode + ' United Kingdom')
      }
    }

    // Place of destination – from search selection or same as consignee
    const placeOfDestinationId = req.query.placeOfDestination
    if (req.query.removePlaceOfDestination === '1') {
      delete data.placeOfDestinationId
      delete data.placeOfDestinationName
      delete data.placeOfDestinationAddress
      delete data.placeOfDestinationCountry
      delete data.placeOfDestinationType
    } else if (req.query.placeOfDestinationSameAsConsignee === '1') {
      const hasConsigneeFromSearch = !!(data.consigneeId && data.consigneeName && data.consigneeAddress && data.consigneeCountry)
      const hasConsigneeFromForm = !!(data.consigneeName && data.consigneeAddressLine1 && data.consigneeTown && data.consigneePostcode)
      if (hasConsigneeFromSearch) {
        delete data.placeOfDestinationId
        data.placeOfDestinationName = data.consigneeName
        data.placeOfDestinationAddress = data.consigneeAddress
        data.placeOfDestinationCountry = data.consigneeCountry
        delete data.placeOfDestinationType
      } else if (hasConsigneeFromForm) {
        delete data.placeOfDestinationId
        data.placeOfDestinationName = data.consigneeName
        data.placeOfDestinationAddressLine1 = data.consigneeAddressLine1
        data.placeOfDestinationAddressLine2 = data.consigneeAddressLine2
        data.placeOfDestinationTown = data.consigneeTown
        data.placeOfDestinationPostcode = data.consigneePostcode
        data.placeOfDestinationCountry = 'United Kingdom'
        delete data.placeOfDestinationAddress
        delete data.placeOfDestinationType
      }
    } else if (placeOfDestinationId) {
      const placesOfDestination = require('../../data/places-of-destination.js')
      const selected = placesOfDestination.find(p => String(p.id) === String(placeOfDestinationId))
      if (selected) {
        data.placeOfDestinationId = selected.id
        data.placeOfDestinationName = selected.name
        data.placeOfDestinationAddress = selected.address
        data.placeOfDestinationCountry = selected.country
        data.placeOfDestinationType = selected.type
      }
    }
    const hasPlaceOfDestination = !!(data.placeOfDestinationName && (data.placeOfDestinationAddress || data.placeOfDestinationAddressLine1))
    const placeOfDestinationAddressLines = []
    if (hasPlaceOfDestination) {
      if (data.placeOfDestinationAddress) {
        placeOfDestinationAddressLines.push(data.placeOfDestinationName, data.placeOfDestinationAddress, (data.placeOfDestinationCountry || '') + (data.placeOfDestinationType ? ' (' + data.placeOfDestinationType + ')' : ''))
      } else {
        if (data.placeOfDestinationName) placeOfDestinationAddressLines.push(data.placeOfDestinationName)
        if (data.placeOfDestinationAddressLine1) placeOfDestinationAddressLines.push(data.placeOfDestinationAddressLine1)
        if (data.placeOfDestinationAddressLine2) placeOfDestinationAddressLines.push(data.placeOfDestinationAddressLine2)
        if (data.placeOfDestinationTown) placeOfDestinationAddressLines.push(data.placeOfDestinationTown)
        if (data.placeOfDestinationPostcode) placeOfDestinationAddressLines.push(data.placeOfDestinationPostcode + ' United Kingdom')
      }
    }

    // Same as consignee for place of destination: show when consignee exists and place is empty or different
    const placeOfDestinationMatchesConsignee = hasConsignee && hasPlaceOfDestination && (
      (data.placeOfDestinationName === data.consigneeName && data.placeOfDestinationAddress === data.consigneeAddress) ||
      (data.placeOfDestinationName === data.consigneeName && data.placeOfDestinationAddressLine1 === data.consigneeAddressLine1 && data.placeOfDestinationTown === data.consigneeTown)
    )
    const showSameAsConsigneeForDestination = hasConsignee && !placeOfDestinationMatchesConsignee

    res.render('v2-post-baseline/create/addresses', {
      consignorName,
      consignorAddress,
      consignorCountry,
      hasConsignor,
      hasConsignee,
      consigneeAddressLines,
      hasImporter,
      importerAddressLines,
      showSameAsConsignee,
      hasPlaceOfDestination,
      placeOfDestinationAddressLines,
      showSameAsConsigneeForDestination
    })
  })

  router.post(`${BASE}/create/addresses`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/address-cph`)
  })

  router.get(`${BASE}/create/address-cph`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList
    res.render('v2-post-baseline/create/address-cph')
  })

  router.post(`${BASE}/create/address-cph`, (req, res) => {
    const data = req.session.data || {}
    const cphNumber = (data.cphNumber || '').trim()
    const errors = {}
    const errorList = []
    if (!cphNumber) {
      errors.cphNumber = 'Enter the CPH number'
      errorList.push({ href: '#cphNumber', text: 'Enter the CPH number' })
    }
    if (errorList.length > 0) {
      data.errors = errors
      data.errorList = errorList
      return res.redirect(`${BASE}/create/address-cph`)
    }
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/contact-address-for-consignment`)
  })

  router.get(`${BASE}/create/address-cph-prefill`, (req, res) => {
    const data = req.session.data || {}
    data.cphNumber = '12/345/6789'
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/contact-address-for-consignment`)
  })

  router.get(`${BASE}/create/contact-address-for-consignment`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList
    const contactAddresses = require('../../data/contact-addresses.js')
    const contactAddressItems = contactAddresses.map((addr) => {
      const lines = [addr.name, ...(addr.addressLines || [addr.address] || [])]
      if (addr.country) lines.push(addr.country)
      const html = lines.join('<br>')
      return {
        value: String(addr.id),
        html
      }
    })
    res.render('v2-post-baseline/create/contact-address-for-consignment', {
      contactAddressItems
    })
  })

  router.post(`${BASE}/create/contact-address-for-consignment`, (req, res) => {
    const data = req.session.data || {}
    const contactAddressId = (data.contactAddressId || '').trim()
    const errors = {}
    const errorList = []
    if (!contactAddressId) {
      errors.contactAddressId = 'Select an address'
      errorList.push({ href: '#contact-address-1', text: 'Select an address' })
    }
    if (errorList.length > 0) {
      data.errors = errors
      data.errorList = errorList
      return res.redirect(`${BASE}/create/contact-address-for-consignment`)
    }
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/transport-arrival`)
  })

  router.get(`${BASE}/create/contact-address-for-consignment-prefill`, (req, res) => {
    const data = req.session.data || {}
    data.contactAddressId = '1'
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/transport-arrival`)
  })

  router.get(`${BASE}/create/transport-arrival`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList
    const d = new Date()
    d.setDate(d.getDate() + 3)
    const minArrivalDate = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
    res.render('v2-post-baseline/create/transport-arrival', {
      minArrivalDate,
      defaultArrivalDate: minArrivalDate
    })
  })

  router.post(`${BASE}/create/transport-arrival`, (req, res) => {
    const data = req.session.data || {}
    const arrivalDate = (data.arrivalDate || '').trim()
    const errors = {}
    const errorList = []
    if (!arrivalDate) {
      errors.arrivalDate = 'Enter the arrival date'
      errorList.push({ href: '#arrivalDate', text: 'Enter the arrival date' })
    }
    if (errorList.length > 0) {
      data.errors = errors
      data.errorList = errorList
      return res.redirect(`${BASE}/create/transport-arrival`)
    }
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/transport-transporter`)
  })

  router.get(`${BASE}/create/transport-arrival-prefill`, (req, res) => {
    const data = req.session.data || {}
    const d = new Date()
    d.setDate(d.getDate() + 3)
    data.arrivalDate = `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/transport-transporter`)
  })

  router.get(`${BASE}/create/transport-transporter`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList

    // Store selected transporter when returning from address-consignee-search?returnTo=transport-transporter
    const transporterId = req.query.transporter
    if (req.query.removeTransporter === '1') {
      delete data.transporterId
      delete data.transporterName
      delete data.transporterAddress
      delete data.transporterCountry
      delete data.transporterType
      delete data.transporterApprovalNumber
      delete data.transporterAddressLine1
      delete data.transporterAddressLine2
      delete data.transporterTown
      delete data.transporterPostcode
    } else if (transporterId) {
      const consignees = require('../../data/consignees.js')
      const selected = consignees.find(c => String(c.id) === String(transporterId))
      if (selected) {
        data.transporterId = selected.id
        data.transporterName = selected.name
        data.transporterAddress = selected.address
        data.transporterCountry = selected.country
        data.transporterType = selected.transporterType || ''
        data.transporterApprovalNumber = selected.approvalNumber || ''
      }
      return res.redirect(`${BASE}/create/transport-transporter`)
    }

    const hasTransporter = !!(data.transporterName && (data.transporterId || data.transporterAddressLine1))
    const typeDisplay = data.transporterType === 'Commercial transporter' ? 'Commercial' : data.transporterType === 'Private transporter' ? 'Private' : ''
    const approvalDisplay = data.transporterType === 'Private transporter' ? 'Not required' : (data.transporterApprovalNumber || '')
    const transporterRows = [
      { key: { text: 'Name' }, value: { html: `<strong>${data.transporterName || ''}</strong>` } },
      { key: { text: 'Address' }, value: { html: (data.transporterAddress || '') + (data.transporterAddress && data.transporterCountry ? '<br>' : '') + (data.transporterCountry || '') } },
      { key: { text: 'Type' }, value: { text: typeDisplay || '—' } }
    ]
    if (typeDisplay !== 'Private') {
      transporterRows.push({ key: { text: 'Approval number' }, value: { text: approvalDisplay || '—' } })
    }
    res.render('v2-post-baseline/create/transport-transporter', {
      hasTransporter,
      transporterName: data.transporterName || '',
      transporterAddress: data.transporterAddress || '',
      transporterCountry: data.transporterCountry || '',
      transporterType: typeDisplay,
      transporterApprovalNumber: approvalDisplay,
      transporterRows
    })
  })

  router.post(`${BASE}/create/transport-transporter`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/check-your-answers`)
  })

  router.get(`${BASE}/create/transport-transporter-prefill`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList
    if (!data.transporterName || !data.transporterType) {
      const consignees = require('../../data/consignees.js')
      const sample = consignees.find(c => c.transporterType) || consignees[0]
      if (sample) {
        data.transporterId = sample.id
        data.transporterName = sample.name
        data.transporterAddress = sample.address
        data.transporterCountry = sample.country
        data.transporterType = sample.transporterType || ''
        data.transporterApprovalNumber = sample.approvalNumber || ''
      }
    }
    // Ensure commodity/species data exists for Check your answers table (avoids empty species table)
    if (!data.commoditySpecies || data.commoditySpecies.length === 0 || !data.quantity_bos_taurus) {
      data.commodity = data.commodity || 'Cow'
      data.commoditySpecies = ['Bos taurus']
      data.commodityType = 'domestic'
      data.quantity_bos_taurus = 24
      data.packages_bos_taurus = 3
    }
    // Ensure documents exist for Check your answers table (avoids empty Accompanying documents table)
    const hasDocuments = data.documents && data.documents.some(d => d && d.type)
    if (!hasDocuments) {
      data.documents = [
        { type: 'veterinary-health-certificate', reference: 'VHC-2024-001', date: '2025-06-14', attachments: [{}] },
        { type: 'commercial-invoice', reference: 'INV-7892', date: '2025-06-14', attachments: [] }
      ]
    }
    res.redirect(`${BASE}/create/check-your-answers`)
  })

  function formatDate (isoDate) {
    if (!isoDate || typeof isoDate !== 'string') return isoDate || 'Not provided'
    const [y, m, d] = isoDate.split('-').map(Number)
    const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    return `${d} ${months[m - 1]} ${y}`
  }

  function buildCheckYourAnswersData (data) {
    const row = (key, value) => ({ key: { text: key }, value: { text: value } })
    const rowHtml = (key, html) => ({ key: { text: key }, value: { html } })
    const escapeHtml = (s) => typeof s !== 'string' ? '' : String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
    const formatAddressHtml = (name, address, country) => {
      const parts = []
      if (name) parts.push(`<strong>${escapeHtml(name)}</strong>`)
      const addrLines = Array.isArray(address) ? address.filter(Boolean) : (address ? String(address).split(',').map(s => s.trim()).filter(Boolean) : [])
      addrLines.forEach(line => parts.push(escapeHtml(line)))
      if (country) parts.push(escapeHtml(country))
      return parts.length ? parts.join('<br>') : 'Not provided'
    }
    const documentTypes = require('../../data/document-types.js')
    const getDocumentTypeLabel = (val) => (documentTypes.find(d => d.value === val) || {}).text || val || 'Not provided'

    // Type of goods (import-type page)
    const importTypeLabel = { 'live-animals': 'Live animals', 'animal-products': 'Animal products' }[data.importType] || data.importType || 'Not provided'
    const typeOfGoodsRows = [row('Type of goods', importTypeLabel)]

    // Origin of the import (origin page) – matches form fields: country, region of origin, internal reference (optional)
    const originRows = [
      row('Country of origin', data.countryOfOrigin || 'Not provided'),
      row('Region of origin code', data.regionOfOriginRequired === 'yes' ? (data.regionOfOriginCode || 'Not provided') : 'Not required')
    ]
    const refNum = (data.consignmentReference || '').trim()
    if (refNum) originRows.push(row('Your internal reference number', refNum))

    // Import reason (import-reason page) – matches form: main reason + purpose when internal market
    const mainReasonLabels = { 'internal-market': 'Internal market', 're-entry': 'Re-entry', 'temporary-admission-horses': 'Temporary admission (horses)' }
    const mainReasonLabel = mainReasonLabels[data.importReason] || data.importReason || 'Not provided'
    const importReasonRows = [row('Main reason for importing the animals', mainReasonLabel)]
    if (data.importReason === 'internal-market' && data.internalMarketPurpose) {
      const purposes = require('../../data/internal-market-purposes.js')
      const purpose = purposes.find(p => p.value === data.internalMarketPurpose)
      importReasonRows.push(row('Purpose in the internal market', purpose ? purpose.text : data.internalMarketPurpose))
    }

    // Description of the goods – commodity info + table: Species | Number of animals | Number of packages
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = data.commodity ? commoditiesData[data.commodity] : null
    const descriptionSummaryRows = []
    if (commodityDetails) {
      descriptionSummaryRows.push(row('Commodity code', commodityDetails.code || 'Not provided'))
      descriptionSummaryRows.push(row('Common name', commodityDetails.commonName || data.commodity || 'Not provided'))
      descriptionSummaryRows.push(row('Description', commodityDetails.description || 'Not provided'))
    }
    // Normalise to array: checkboxes can return a string when only one is selected (body-parser quirk)
    const rawSpecies = data.commoditySpecies
    const commoditySpecies = Array.isArray(rawSpecies) ? rawSpecies : (rawSpecies ? [rawSpecies] : [])
    const typeLabel = data.commodityType === 'game' ? 'Game' : 'Domestic'
    const descriptionTableRows = []
    let totalAnimals = 0
    let totalPackages = 0
    const toKey = (s) => String(s || '').replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
    commoditySpecies.forEach(s => {
      const key = toKey(s)
      const qty = parseInt(data[`quantity_${key}`], 10) || 0
      const pkg = parseInt(data[`packages_${key}`], 10) || 0
      totalAnimals += qty
      totalPackages += pkg
      descriptionTableRows.push([
        { text: `${s}, ${typeLabel}` },
        { text: String(qty), format: 'numeric' },
        { text: String(pkg), format: 'numeric' }
      ])
    })
    const hasNoDescriptionData = !data.commodity || commoditySpecies.length === 0 || (totalAnimals === 0 && totalPackages === 0)
    if (hasNoDescriptionData) {
      // Dummy data for prototype when no session data (e.g. direct link or all zeros)
      descriptionTableRows.length = 0
      descriptionTableRows.push(
        [{ text: 'Bos taurus, Domestic' }, { text: '24', format: 'numeric' }, { text: '3', format: 'numeric' }],
        [{ text: 'Ovis aries, Domestic' }, { text: '12', format: 'numeric' }, { text: '2', format: 'numeric' }],
        [{ text: 'Total', classes: 'govuk-table__header' }, { text: '36', format: 'numeric' }, { text: '5', format: 'numeric' }]
      )
    } else {
      descriptionTableRows.push([
        { text: 'Total', classes: 'govuk-table__header' },
        { text: String(totalAnimals), format: 'numeric' },
        { text: String(totalPackages), format: 'numeric' }
      ])
    }

    // County Parish Holding number (CPH) (address-cph page)
    const cphRows = [row('County Parish Holding number (CPH)', data.cphNumber || 'Not provided')]

    // Animal identification – first species/animal as summary, or placeholder
    const animalIdRows = []
    if (commoditySpecies.length > 0) {
      const key = commoditySpecies[0].replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      const earTag1 = data[`earTag_${key}_1`] || 'Not provided'
      const passport1 = data[`passport_${key}_1`] || 'Not provided'
      animalIdRows.push(row('Identification device', 'Ear tag\nPassport'))
      animalIdRows.push(row('Animal', `${commoditySpecies[0]}, ${typeLabel}`))
      animalIdRows.push(row('Identification 1', `${earTag1}\n${passport1}`))
      if (data[`earTag_${key}_2`] || data[`passport_${key}_2`]) {
        animalIdRows.push(row('Identification 2', `${data[`earTag_${key}_2`] || '-'}\n${data[`passport_${key}_2`] || '-'}`))
      }
    }
    if (animalIdRows.length === 0) {
      animalIdRows.push(row('Details', 'Not yet provided'))
    }

    // Additional animal details
    const certLabels = { 'approved-bodies': 'Approved bodies', 'breeding-production': 'Breeding and/or production', 'slaughter': 'Slaughter' }
    const unweanedLabel = data.unweanedAnimals === 'yes' ? 'Yes' : data.unweanedAnimals === 'no' ? 'No' : 'Not provided'
    const additionalAnimalRows = [
      row('Certificate for', certLabels[data.animalsCertifiedFor] || data.animalsCertifiedFor || 'Not provided'),
      row('Unweaned animals', unweanedLabel)
    ]

    // Documents table – cells must be objects { text: '...' } for GOV.UK table macro
    const docs = data.documents || []
    const cell = (t) => ({ text: String(t ?? '-') })
    let documentsTableRows = docs.filter(d => d.type).map(d => [
      cell(getDocumentTypeLabel(d.type)),
      cell(d.reference),
      cell(d.date ? formatDate(d.date) : '-'),
      cell((d.attachments && d.attachments.length) ? `${d.attachments.length} attachment${d.attachments.length !== 1 ? 's' : ''}` : '-')
    ])
    if (documentsTableRows.length === 0) {
      documentsTableRows = [
        [cell('Veterinary health certificate'), cell('VHC-2024-001'), cell('14 June 2025'), cell('1 attachment')],
        [cell('Commercial invoice'), cell('INV-7892'), cell('14 June 2025'), cell('-')],
        [cell('Import permit'), cell('GB-IMP-2024-456'), cell('1 September 2025'), cell('2 attachments')]
      ]
    }

    // Addresses – company name bold, address on new lines
    const consignorAddr = formatAddressHtml(data.consignorName, data.consignorAddress, data.consignorCountry)
    const consigneeAddr = data.consigneeAddress
      ? formatAddressHtml(data.consigneeName, data.consigneeAddress, data.consigneeCountry)
      : formatAddressHtml(data.consigneeName, [data.consigneeAddressLine1, data.consigneeAddressLine2, data.consigneeTown, data.consigneePostcode].filter(Boolean), null) || (data.consigneeName ? formatAddressHtml(data.consigneeName, null, null) : 'Not provided')
    const importerAddr = data.importerAddress
      ? formatAddressHtml(data.importerName, data.importerAddress, data.importerCountry)
      : formatAddressHtml(data.importerName, [data.importerAddressLine1, data.importerAddressLine2, data.importerTown, data.importerPostcode].filter(Boolean), null) || (data.importerName ? formatAddressHtml(data.importerName, null, null) : 'Not provided')
    const placeAddr = data.placeOfDestinationAddress
      ? formatAddressHtml(data.placeOfDestinationName, data.placeOfDestinationAddress, data.placeOfDestinationCountry)
      : formatAddressHtml(data.placeOfDestinationName, [data.placeOfDestinationAddressLine1, data.placeOfDestinationAddressLine2, data.placeOfDestinationTown, data.placeOfDestinationPostcode].filter(Boolean), null) || (data.placeOfDestinationName ? formatAddressHtml(data.placeOfDestinationName, null, null) : 'Not provided')

    const addressRows = [
      rowHtml('Consignor or exporter', consignorAddr),
      rowHtml('Consignee', consigneeAddr),
      rowHtml('Importer', importerAddr),
      rowHtml('Place of destination', placeAddr)
    ]
    if (data.consigneeBusinessRegistration) {
      addressRows.push(row('Consignee business registration', data.consigneeBusinessRegistration))
    }

    // Contact address
    const contactAddresses = require('../../data/contact-addresses.js')
    const selectedContact = data.contactAddressId && contactAddresses.find(c => String(c.id) === String(data.contactAddressId))
    const contactAddrHtml = selectedContact
      ? formatAddressHtml(selectedContact.name, selectedContact.addressLines || [], selectedContact.country)
      : (data.consignorName ? formatAddressHtml(data.consignorName, data.consignorAddress, data.consignorCountry) : 'Not provided')
    const contactAddressRows = [rowHtml('Contact address', contactAddrHtml)]

    // Transport – split into Arrival at destination and Transporter (each with own Change link)
    let transporterTypeDisplay = data.transporterType
    if (!transporterTypeDisplay) {
      const consignees = require('../../data/consignees.js')
      const normalize = (s) => (s || '').trim().toLowerCase().replace(/\./g, '').replace(/\s+/g, ' ')
      const nameA = normalize(data.transporterName)
      const addrA = normalize(data.transporterAddress)
      const transporterRecord = data.transporterId
        ? consignees.find(c => String(c.id) === String(data.transporterId))
        : consignees.find(c => {
            const matchName = c.name && nameA && normalize(c.name) === nameA
            const matchAddr = c.address && addrA && normalize(c.address) === addrA
            return matchName || matchAddr
          })
      transporterTypeDisplay = transporterRecord && transporterRecord.transporterType ? transporterRecord.transporterType : null
    }
    transporterTypeDisplay = transporterTypeDisplay
      ? (transporterTypeDisplay === 'Commercial transporter'
        ? 'Commercial transporter'
        : transporterTypeDisplay === 'Private transporter'
          ? 'Private transporter'
          : transporterTypeDisplay)
      : 'Not provided'
    const arrivalRows = [
      row('Arrival date', formatDate(data.arrivalDate))
    ]
    const transporterAddrHtml = formatAddressHtml(
      data.transporterName,
      data.transporterAddress || [data.transporterAddressLine1, data.transporterAddressLine2, data.transporterTown, data.transporterPostcode].filter(Boolean),
      data.transporterCountry
    )
    const transporterApprovalDisplay = transporterTypeDisplay === 'Private transporter'
      ? 'Not required'
      : (data.transporterApprovalNumber || 'Not provided')
    const transporterRows = [
      rowHtml('Details', transporterAddrHtml),
      row('Type', transporterTypeDisplay),
      row('Approval number', transporterApprovalDisplay)
    ]

    return {
      typeOfGoodsRows,
      originRows,
      importReasonRows,
      descriptionSummaryRows,
      descriptionTableRows,
      animalIdRows,
      additionalAnimalRows,
      documentsTableRows,
      addressRows,
      cphRows,
      contactAddressRows,
      arrivalRows,
      transporterRows
    }
  }

  router.get(`${BASE}/create/check-your-answers-prefill`, (req, res) => {
    const d = req.session.data || {}
    d.importType = 'live-animals'
    d.countryOfOrigin = 'France'
    d.regionOfOriginRequired = 'no'
    d.designatedArrivalPoint = 'Dover'
    d.importReason = 'internal-market'
    d.internalMarketPurpose = 'breeding'
    d.requiredRestInterval = 'N/A'
    d.commodity = 'Cow'
    d.commoditySpecies = ['Bos taurus']
    d.commodityType = 'domestic'
    d.quantity_bos_taurus = 24
    d.packages_bos_taurus = 3
    d.earTag_bos_taurus_1 = 'UK123456789000'
    d.passport_bos_taurus_1 = 'GB-2024-001'
    d.animalsCertifiedFor = 'breeding-production'
    d.unweanedAnimals = 'no'
    d.documents = [
      { type: 'veterinary-health-certificate', reference: 'VHC-2024-001', date: '2025-06-14', attachments: [{}] },
      { type: 'commercial-invoice', reference: 'INV-7892', date: '2025-06-14', attachments: [] },
      { type: 'import-permit', reference: 'GB-IMP-2024-456', date: '2025-09-01', attachments: [{}, {}] }
    ]
    d.consignorName = 'Ferme Dupont SAS'
    d.consignorAddress = ['12 Rue de la Ferme', '75001 Paris']
    d.consignorCountry = 'France'
    d.consigneeName = 'Smith Livestock Ltd'
    d.consigneeAddress = ['45 Farm Road', 'Canterbury', 'CT1 2AB']
    d.consigneeCountry = 'United Kingdom'
    d.importerName = 'Smith Livestock Ltd'
    d.importerAddress = ['45 Farm Road', 'Canterbury', 'CT1 2AB']
    d.importerCountry = 'United Kingdom'
    d.placeOfDestinationName = 'Greenfield Farm'
    d.placeOfDestinationAddress = ['Marsh Lane', 'Ashford', 'TN25 4PQ']
    d.placeOfDestinationCountry = 'United Kingdom'
    d.cphNumber = '12/345/6789'
    d.contactAddressLine1 = '45 Farm Road'
    d.contactAddressTown = 'Canterbury'
    d.contactAddressPostcode = 'CT1 2AB'
    d.arrivalDate = '2025-06-15'
    d.transporterName = 'EuroHaul Transport Ltd'
    d.transporterAddress = ['10 Depot Way', 'Folkestone', 'CT19 5AB']
    d.transporterCountry = 'United Kingdom'
    d.transporterType = 'Haulier'
    d.transporterApprovalNumber = 'GB-AP-2024-123'
    delete d.errors
    delete d.errorList
    res.redirect(`${BASE}/create/check-your-answers`)
  })
  router.get(`${BASE}/create/check-your-answers`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList
    const viewData = buildCheckYourAnswersData(data)
    res.render('v2-post-baseline/create/check-your-answers', viewData)
  })

  router.post(`${BASE}/create/check-your-answers`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/declaration`)
  })

  router.get(`${BASE}/create/declaration`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const now = new Date()
    const declarationDate = `${now.getDate()} ${['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'][now.getMonth()]} ${now.getFullYear()}`
    res.render('v2-post-baseline/create/declaration', { declarationDate })
  })

  router.post(`${BASE}/create/declaration`, (req, res) => {
    const accepted = req.session.data.declarationAccepted
    const isAccepted = accepted === 'yes' || (Array.isArray(accepted) && accepted.includes('yes'))
    if (!isAccepted) {
      req.session.data.errors = { declarationAccepted: 'You must confirm the declaration to submit' }
      req.session.data.errorList = [{ href: '#declaration-accepted-1', text: 'You must confirm the declaration to submit' }]
      return res.redirect(`${BASE}/create/declaration`)
    }
    delete req.session.data.errors
    delete req.session.data.errorList
    const data = req.session.data || {}
    req.session.data.declarationDate = new Date().toISOString().split('T')[0]
    const year = new Date().getFullYear()
    const suffix = String(Math.floor(1000000 + Math.random() * 9000000))
    const referenceNumber = `IMP.GB.${year}.${suffix}`
    req.session.data.lastReferenceNumber = referenceNumber

    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = data.commodity ? commoditiesData[data.commodity] : null
    const commodityCode = commodityDetails ? commodityDetails.code : (data.commodityCode || '')
    const commodityName = (data.commoditySpecies && data.commoditySpecies[0]) || 'Live animals'
    const commodityDisplay = commodityCode ? `${commodityName} (${commodityCode})` : commodityName

    const submitted = {
      reference: referenceNumber,
      commodity: commodityDisplay,
      origin: data.countryOfOrigin || 'Not provided',
      consignee: data.consigneeName || (data.consignee && data.consignee.name) || 'Not provided',
      consignor: data.consignorName || (data.consignor && data.consignor.name) || 'Not provided',
      arrival: formatDate(data.arrivalDate) || 'Not provided',
      status: 'submitted'
    }
    if (!Array.isArray(data.submittedNotifications)) data.submittedNotifications = []
    data.submittedNotifications.push(submitted)

    res.redirect(`${BASE}/create/confirmation`)
  })

  router.get(`${BASE}/create/confirmation`, (req, res) => {
    const referenceNumber = req.session.data.lastReferenceNumber
    res.render('v2-post-baseline/create/confirmation', { referenceNumber })
  })

  router.get(`${BASE}/create/confirmation-prefill`, (req, res) => {
    const year = new Date().getFullYear()
    const suffix = String(Math.floor(1000000 + Math.random() * 9000000))
    req.session.data.lastReferenceNumber = `IMP.GB.${year}.${suffix}`
    res.redirect(`${BASE}/create/confirmation`)
  })

  router.get(`${BASE}/create/declaration-prefill`, (req, res) => {
    req.session.data.declarationAccepted = 'yes'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/declaration`)
  })

  router.get(`${BASE}/create/transport-add-transporter`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList
    const euCountries = require('../../data/eu-countries.js')
    const countryItems = [{ value: '', text: 'Select country' }, { value: 'United Kingdom', text: 'United Kingdom' }].concat(
      euCountries.map(c => ({ value: c, text: c }))
    )
    res.render('v2-post-baseline/create/transport-add-transporter', { countryItems })
  })

  router.post(`${BASE}/create/transport-add-transporter`, (req, res) => {
    const data = req.session.data || {}
    const transporterName = (data.transporterName || '').trim()
    const transporterAddressLine1 = (data.transporterAddressLine1 || '').trim()
    const transporterAddressLine2 = (data.transporterAddressLine2 || '').trim()
    const transporterTown = (data.transporterTown || '').trim()
    const transporterPostcode = (data.transporterPostcode || '').trim()
    const transporterCountry = (data.transporterCountry || '').trim()

    const errors = {}
    const errorList = []
    if (!transporterName) {
      errors.transporterName = 'Enter the name or organisation'
      errorList.push({ href: '#transporterName', text: 'Enter the name or organisation' })
    }
    if (!transporterAddressLine1) {
      errors.transporterAddressLine1 = 'Enter address line 1'
      errorList.push({ href: '#transporterAddressLine1', text: 'Enter address line 1' })
    }
    if (!transporterTown) {
      errors.transporterTown = 'Enter the town or city'
      errorList.push({ href: '#transporterTown', text: 'Enter the town or city' })
    }
    if (!transporterCountry) {
      errors.transporterCountry = 'Select a country'
      errorList.push({ href: '#transporterCountry', text: 'Select a country' })
    } else if (transporterCountry === 'United Kingdom' && !transporterPostcode) {
      errors.transporterPostcode = 'Enter the postcode'
      errorList.push({ href: '#transporterPostcode', text: 'Enter the postcode' })
    }

    if (errorList.length > 0) {
      data.errors = errors
      data.errorList = errorList
      const euCountries = require('../../data/eu-countries.js')
      const countryItems = [{ value: '', text: 'Select country' }, { value: 'United Kingdom', text: 'United Kingdom' }].concat(
        euCountries.map(c => ({ value: c, text: c }))
      )
      return res.redirect(`${BASE}/create/transport-add-transporter`)
    }

    delete data.transporterId
    const addressParts = [transporterAddressLine1, transporterAddressLine2, transporterTown, transporterPostcode].filter(Boolean)
    data.transporterAddress = addressParts.join(', ') + ', ' + transporterCountry
    data.transporterCountry = transporterCountry
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/transport-transporter`)
  })

  router.get(`${BASE}/create/transport`, (req, res) => {
    res.redirect(`${BASE}/create/transport-arrival`)
  })

  router.get(`${BASE}/create/address-consignee`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList
    res.render('v2-post-baseline/create/address-consignee')
  })

  router.post(`${BASE}/create/address-consignee`, (req, res) => {
    const data = req.session.data || {}
    const consigneeName = (data.consigneeName || '').trim()
    const consigneeAddressLine1 = (data.consigneeAddressLine1 || '').trim()
    const consigneeTown = (data.consigneeTown || '').trim()
    const consigneePostcode = (data.consigneePostcode || '').trim()

    const errors = {}
    const errorList = []
    if (!consigneeName) {
      errors.consigneeName = 'Enter the name or organisation'
      errorList.push({ href: '#consigneeName', text: 'Enter the name or organisation' })
    }
    if (!consigneeAddressLine1) {
      errors.consigneeAddressLine1 = 'Enter address line 1'
      errorList.push({ href: '#consigneeAddressLine1', text: 'Enter address line 1' })
    }
    if (!consigneeTown) {
      errors.consigneeTown = 'Enter the town or city'
      errorList.push({ href: '#consigneeTown', text: 'Enter the town or city' })
    }
    if (!consigneePostcode) {
      errors.consigneePostcode = 'Enter the postcode'
      errorList.push({ href: '#consigneePostcode', text: 'Enter the postcode' })
    }

    if (errorList.length > 0) {
      data.errors = errors
      data.errorList = errorList
      return res.redirect(`${BASE}/create/address-consignee`)
    }

    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/addresses`)
  })

  router.get(`${BASE}/create/address-consignee-search`, (req, res) => {
    const data = req.session.data || {}
    const consignees = require('../../data/consignees.js')
    const returnTo = req.query.returnTo || ''
    const isTransporter = returnTo === 'transport-transporter'
    const page = parseInt(req.query.page, 10) || 1
    const perPage = 10

    let filtered = consignees
    if (isTransporter) {
      const searchName = (req.query.searchName || data.searchTransporterName || '').trim().toLowerCase()
      const searchApprovalNumber = (req.query.searchApprovalNumber || data.searchTransporterApprovalNumber || '').trim().toLowerCase()
      const searchPostCode = (req.query.searchPostCode || data.searchTransporterPostCode || '').trim().toLowerCase().replace(/\s+/g, ' ')
      data.searchTransporterName = req.query.searchName ?? data.searchTransporterName
      data.searchTransporterApprovalNumber = req.query.searchApprovalNumber ?? data.searchTransporterApprovalNumber
      data.searchTransporterPostCode = req.query.searchPostCode ?? data.searchTransporterPostCode
      if (searchName) {
        filtered = filtered.filter(c => c.name.toLowerCase().includes(searchName))
      }
      if (searchApprovalNumber) {
        filtered = filtered.filter(c => (c.approvalNumber || '').toLowerCase().includes(searchApprovalNumber))
      }
      if (searchPostCode) {
        filtered = filtered.filter(c => (c.postCode || '').toLowerCase().replace(/\s+/g, ' ').includes(searchPostCode))
      }
    } else {
      const searchName = (req.query.searchName || data.searchConsigneeName || '').trim().toLowerCase()
      const searchAddress = (req.query.searchAddress || data.searchConsigneeAddress || '').trim().toLowerCase()
      const searchCountry = (req.query.searchCountry || data.searchConsigneeCountry || '').trim()
      data.searchConsigneeName = req.query.searchName ?? data.searchConsigneeName
      data.searchConsigneeAddress = req.query.searchAddress ?? data.searchConsigneeAddress
      data.searchConsigneeCountry = req.query.searchCountry ?? data.searchConsigneeCountry
      if (searchName) {
        filtered = filtered.filter(c => c.name.toLowerCase().includes(searchName))
      }
      if (searchAddress) {
        filtered = filtered.filter(c => c.address.toLowerCase().includes(searchAddress))
      }
      if (searchCountry) {
        filtered = filtered.filter(c => c.country === searchCountry)
      }
    }

    const total = filtered.length
    const totalPages = Math.max(1, Math.ceil(total / perPage))
    const pageNum = Math.max(1, Math.min(page, totalPages))
    const start = (pageNum - 1) * perPage
    const results = filtered.slice(start, start + perPage)

    const countries = [...new Set(consignees.map(c => c.country))].sort()

    const forImporter = req.query.for === 'importer'
    res.render('v2-post-baseline/create/address-consignee-search', {
      results,
      countries,
      page: pageNum,
      totalPages,
      total,
      forImporter,
      returnTo
    })
  })

  router.get(`${BASE}/create/address-place-of-destination-search`, (req, res) => {
    const data = req.session.data || {}
    const placesOfDestination = require('../../data/places-of-destination.js')
    const searchName = (req.query.searchName || data.searchPlaceOfDestinationName || '').trim().toLowerCase()
    const searchAddress = (req.query.searchAddress || data.searchPlaceOfDestinationAddress || '').trim().toLowerCase()
    const searchType = (req.query.searchType || data.searchPlaceOfDestinationType || '').trim()
    const searchCountry = (req.query.searchCountry || data.searchPlaceOfDestinationCountry || '').trim()
    const page = parseInt(req.query.page, 10) || 1
    const perPage = 10

    data.searchPlaceOfDestinationName = req.query.searchName ?? data.searchPlaceOfDestinationName
    data.searchPlaceOfDestinationAddress = req.query.searchAddress ?? data.searchPlaceOfDestinationAddress
    data.searchPlaceOfDestinationType = req.query.searchType ?? data.searchPlaceOfDestinationType
    data.searchPlaceOfDestinationCountry = req.query.searchCountry ?? data.searchPlaceOfDestinationCountry

    let filtered = placesOfDestination
    if (searchName) {
      filtered = filtered.filter(p => p.name.toLowerCase().includes(searchName))
    }
    if (searchAddress) {
      filtered = filtered.filter(p => p.address.toLowerCase().includes(searchAddress))
    }
    if (searchType) {
      filtered = filtered.filter(p => p.type === searchType)
    }
    if (searchCountry) {
      filtered = filtered.filter(p => p.country === searchCountry)
    }

    const total = filtered.length
    const totalPages = Math.max(1, Math.ceil(total / perPage))
    const pageNum = Math.max(1, Math.min(page, totalPages))
    const start = (pageNum - 1) * perPage
    const results = filtered.slice(start, start + perPage)

    const countries = [...new Set(placesOfDestination.map(p => p.country))].sort()
    const types = [...new Set(placesOfDestination.map(p => p.type))].sort()

    res.render('v2-post-baseline/create/address-place-of-destination-search', {
      results,
      countries,
      types,
      page: pageNum,
      totalPages,
      total
    })
  })

  router.get(`${BASE}/create/address-consignor-search`, (req, res) => {
    const data = req.session.data || {}
    const consignors = require('../../data/consignors.js')
    const euCountries = require('../../data/eu-countries.js')
    const searchName = (req.query.searchName || data.searchName || '').trim().toLowerCase()
    const searchAddress = (req.query.searchAddress || data.searchAddress || '').trim().toLowerCase()
    const searchCountry = (req.query.searchCountry || data.searchCountry || '').trim()
    const page = parseInt(req.query.page, 10) || 1
    const perPage = 10

    data.searchName = req.query.searchName ?? data.searchName
    data.searchAddress = req.query.searchAddress ?? data.searchAddress
    data.searchCountry = req.query.searchCountry ?? data.searchCountry

    let filtered = consignors
    if (searchName) {
      filtered = filtered.filter(c => c.name.toLowerCase().includes(searchName))
    }
    if (searchAddress) {
      filtered = filtered.filter(c => c.address.toLowerCase().includes(searchAddress))
    }
    if (searchCountry) {
      filtered = filtered.filter(c => c.country === searchCountry)
    }

    const total = filtered.length
    const totalPages = Math.max(1, Math.ceil(total / perPage))
    const pageNum = Math.max(1, Math.min(page, totalPages))
    const start = (pageNum - 1) * perPage
    const results = filtered.slice(start, start + perPage)

    const countriesFromData = [...new Set(consignors.map(c => c.country))]
    const countries = [...new Set([...euCountries, ...countriesFromData])].sort()

    res.render('v2-post-baseline/create/address-consignor-search', {
      results,
      countries,
      page: pageNum,
      totalPages,
      total
    })
  })

  router.get(`${BASE}/create/accompanying-documents-prefill`, (req, res) => {
    const data = req.session.data
    data.documents = [{
      type: 'veterinary-health-certificate',
      reference: 'CHED-PP-2024-001',
      date: '2024-03-15',
      attachments: ['Sample health certificate.pdf']
    }]
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/addresses`)
  })

  router.get(`${BASE}/create/address-prefill`, (req, res) => {
    const data = req.session.data || {}
    const consignors = require('../../data/consignors.js')
    const consignees = require('../../data/consignees.js')
    const placesOfDestination = require('../../data/places-of-destination.js')
    const consignor = consignors[0]
    const consignee = consignees[0]
    const place = placesOfDestination[0]
    data.consignorId = consignor.id
    data.consignorName = consignor.name
    data.consignorAddress = consignor.address
    data.consignorCountry = consignor.country
    data.consigneeId = consignee.id
    data.consigneeName = consignee.name
    data.consigneeAddress = consignee.address
    data.consigneeCountry = consignee.country
    data.importerId = consignee.id
    data.importerName = consignee.name
    data.importerAddress = consignee.address
    data.importerCountry = consignee.country
    data.placeOfDestinationId = place.id
    data.placeOfDestinationName = place.name
    data.placeOfDestinationAddress = place.address
    data.placeOfDestinationCountry = place.country
    data.placeOfDestinationType = place.type
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/address-cph`)
  })

  router.post(`${BASE}/create/animal-identification`, (req, res) => {
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const commodityType = req.session.data.commodityType || 'domestic'
    const typeLabel = commodityType === 'game' ? 'Game' : 'Domestic'
    const speciesRows = commoditySpecies.map(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      const quantityKey = `quantity_${key}`
      const quantity = parseInt(req.session.data[quantityKey], 10) || 0
      const animals = []
      for (let i = 1; i <= quantity; i++) {
        animals.push({
          index: i,
          earTagKey: `earTag_${key}_${i}`,
          passportKey: `passport_${key}_${i}`
        })
      }
      return {
        key,
        speciesAndType: `${s}, ${typeLabel}`,
        quantity,
        animals
      }
    })

    const errors = {}
    const errorList = []
    speciesRows.forEach(s => {
      s.animals.forEach(a => {
        const earTagVal = req.session.data[a.earTagKey]
        const passportVal = req.session.data[a.passportKey]
        const earTagMissing = !earTagVal || String(earTagVal).trim() === ''
        const passportMissing = !passportVal || String(passportVal).trim() === ''

        if (earTagMissing) errors[a.earTagKey] = 'Enter the ear tag number'
        if (passportMissing) errors[a.passportKey] = 'Enter the passport number'

        if (earTagMissing || passportMissing) {
          const animalLabel = `${s.speciesAndType} animal ${a.index}`
          const missingParts = []
          if (earTagMissing) missingParts.push('ear tag')
          if (passportMissing) missingParts.push('passport')
          const message = missingParts.length === 2
            ? `Enter the ear tag and passport for ${animalLabel}`
            : `Enter the ${missingParts[0]} for ${animalLabel}`
          errorList.push({ href: `#ear-tag-${a.earTagKey}`, text: message })
        }
      })
    })

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/animal-identification`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/additional-animal-details`)
  })

  router.get(`${BASE}/clear-filters`, (req, res) => {
    FILTER_KEYS.forEach(key => delete req.session.data[key])
    delete req.session.data.sort
    res.redirect(`${BASE}/dashboard`)
  })
}
