//
// For guidance on how to create routes see:
// https://prototype-kit.service.gov.uk/docs/create-routes
//
// Generated by Cursor
//

const govukPrototypeKit = require('govuk-prototype-kit')
const router = govukPrototypeKit.requests.setupRouter()

// Clear session data and redirect back (useful for resetting prototype state)
router.get('/clear-data', (req, res) => {
  req.session.data = {}
  const returnUrl = req.get('Referrer') || '/'
  res.redirect(returnUrl)
})

// Version routes – add new versions here
require('./views/v1-baseline/routes')(router)
require('./views/v2-simplified-flow/routes')(router)
