//
// For guidance on how to create routes see:
// https://prototype-kit.service.gov.uk/docs/create-routes
//
// Generated by Cursor
//

const govukPrototypeKit = require('govuk-prototype-kit')
const router = govukPrototypeKit.requests.setupRouter()

// Index – prototype home (GOV.UK logo links here)
router.get('/', (req, res) => {
  res.render('index')
})

// Sign in – how do you want to sign in?
router.get('/sign-in', (req, res) => {
  res.render('sign-in')
})

router.post('/sign-in', (req, res) => {
  res.redirect('/v1-baseline/dashboard')
})

// Clear session data and redirect back (useful for resetting prototype state)
router.get('/clear-data', (req, res) => {
  req.session.data = {}
  const returnUrl = req.get('Referrer') || '/'
  res.redirect(returnUrl)
})

// Version routes – add new versions here
require('./views/v1-baseline/routes')(router)
require('./views/v2-simplified-flow/routes')(router)
