//
// v1-baseline routes
// Generated by Cursor
//

const BASE = '/v1-baseline'
const notifications = require('../../data/notifications')

const FILTER_KEYS = ['filterKeyword', 'filterCommodity', 'filterOrigin', 'filterConsignee', 'filterDestination', 'filterStatus', 'filterStartDate', 'filterEndDate']

function filterNotifications (filterData) {
  return notifications.filter(n => {
    const keyword = (filterData.keyword || '').trim().toLowerCase()
    if (keyword) {
      const search = `${n.reference} ${n.commodity} ${n.origin} ${n.consignee} ${n.consignor}`.toLowerCase()
      if (!search.includes(keyword)) return false
    }

    const commodity = (filterData.commodity || '').trim().toLowerCase()
    if (commodity && !n.commodity.toLowerCase().includes(commodity)) return false

    const origin = (filterData.origin || '').trim().toLowerCase()
    if (origin && !n.origin.toLowerCase().includes(origin)) return false

    const consignee = (filterData.consignee || '').trim().toLowerCase()
    if (consignee) {
      const match = n.consignee.toLowerCase().includes(consignee) || n.consignor.toLowerCase().includes(consignee)
      if (!match) return false
    }

    const status = (filterData.status || '').trim().toLowerCase()
    if (status && n.status !== status) return false

    return true
  })
}

module.exports = (router) => {
  router.get(`${BASE}/start`, (req, res) => {
    res.render('v1-baseline/start')
  })

  router.get(`${BASE}/dashboard`, (req, res) => {
    const data = req.session.data || {}
    const filterData = {
      keyword: data.filterKeyword,
      commodity: data.filterCommodity,
      origin: data.filterOrigin,
      consignee: data.filterConsignee,
      destination: data.filterDestination,
      status: data.filterStatus,
      startDate: data.filterStartDate,
      endDate: data.filterEndDate
    }
    const filtered = filterNotifications(filterData)
    req.session.data.resultsCount = filtered.length
    res.locals.notifications = filtered
    res.render('v1-baseline/dashboard')
  })

  router.get(`${BASE}/create/import-type`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    res.render('v1-baseline/create/import-type')
  })

  router.post(`${BASE}/create/import-type`, (req, res) => {
    const importType = req.session.data.importType
    if (!importType || importType.trim() === '') {
      req.session.data.errors = { importType: 'Select what you are importing' }
      req.session.data.errorList = [{ href: '#import-type-1', text: 'Select what you are importing' }]
      return res.redirect(`${BASE}/create/import-type`)
    }
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/origin`)
  })

  router.get(`${BASE}/create/import-type-prefill`, (req, res) => {
    req.session.data.importType = 'live-animals'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/origin`)
  })

  router.get(`${BASE}/create/origin`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const euCountries = require('../../data/eu-countries.js')
    const euCountryCodes = require('../../data/eu-country-codes.js')
    res.render('v1-baseline/create/origin', {
      euCountries,
      euCountryCodes
    })
  })

  router.post(`${BASE}/create/origin`, (req, res) => {
    const countryOfOrigin = req.session.data.countryOfOrigin
    const regionOfOriginRequired = req.session.data.regionOfOriginRequired
    const errors = {}
    const errorList = []

    if (!countryOfOrigin || countryOfOrigin.trim() === '') {
      errors.countryOfOrigin = 'Select a country'
      errorList.push({ href: '#countryOfOrigin', text: 'Select a country' })
    }
    if (!regionOfOriginRequired || regionOfOriginRequired.trim() === '') {
      errors.regionOfOriginRequired = 'Select if the consignment requires a region of origin code'
      errorList.push({ href: '#region-of-origin-1', text: 'Select if the consignment requires a region of origin code' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/origin`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity`)
  })

  router.get(`${BASE}/create/origin-prefill`, (req, res) => {
    req.session.data.countryOfOrigin = 'France'
    req.session.data.regionOfOriginRequired = 'no'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity`)
  })

  router.get(`${BASE}/create/commodity`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodities = require('../../data/commodity-list.js')
    res.render('v1-baseline/create/commodity', {
      commodities
    })
  })

  router.post(`${BASE}/create/commodity`, (req, res) => {
    const commodity = req.session.data.commodity
    const errors = {}
    const errorList = []

    if (!commodity || commodity.trim() === '') {
      errors.commodity = 'Select a commodity'
      errorList.push({ href: '#commodity', text: 'Select a commodity' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/commodity`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity-species`)
  })

  router.get(`${BASE}/create/commodity-prefill`, (req, res) => {
    req.session.data.commodity = 'Cow'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity-species`)
  })

  router.get(`${BASE}/create/commodity-species`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodity = req.session.data.commodity
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails) {
      return res.redirect(`${BASE}/create/commodity`)
    }

    const commodityTypeItems = commodityDetails.commodityTypes.map(t => ({
      value: t.toLowerCase(),
      text: t
    }))
    const selectedSpecies = req.session.data.commoditySpecies || []
    const speciesItems = commodityDetails.species.map(s => ({
      value: s,
      text: s,
      checked: selectedSpecies.indexOf(s) !== -1
    }))

    res.render('v1-baseline/create/commodity-species', {
      commodityDetails,
      commodityTypeItems,
      speciesItems
    })
  })

  router.post(`${BASE}/create/commodity-species`, (req, res) => {
    const species = req.session.data.commoditySpecies
    const errors = {}
    const errorList = []

    if (!species || !Array.isArray(species) || species.length === 0) {
      errors.commoditySpecies = 'Select at least one species'
      errorList.push({ href: '#commoditySpecies-1', text: 'Select at least one species' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/import-reason`)
  })

  router.get(`${BASE}/create/commodity-species-prefill`, (req, res) => {
    const commodityDetails = req.session.data.commodity ? require('../../data/commodities.js')[req.session.data.commodity] : null
    // Use Bos taurus (domestic cattle) for Cow; otherwise first species in list
    const species = commodityDetails && req.session.data.commodity === 'Cow'
      ? 'Bos taurus'
      : (commodityDetails ? commodityDetails.species[0] : 'Bos taurus')
    req.session.data.commoditySpecies = [species]
    req.session.data.commodityType = 'domestic'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/import-reason`)
  })

  router.get(`${BASE}/create/import-reason`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commoditySpecies = req.session.data.commoditySpecies || []
    const horseSpecies = require('../../data/commodity-list.js').horseSpecies
    const showTemporaryAdmissionHorses = commoditySpecies.some(s => horseSpecies.includes(s))
    const internalMarketPurposes = require('../../data/internal-market-purposes.js')

    const purposeItems = internalMarketPurposes.map(p => ({
      value: p.value,
      text: p.text,
      hint: p.hint ? { text: p.hint } : undefined,
      checked: req.session.data.internalMarketPurpose === p.value
    }))

    const escapeHtml = (s) => String(s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')

    const purposeError = req.session.data.errors && req.session.data.errors.internalMarketPurpose
    const purposeConditionalHtml = `
      <div class="govuk-form-group govuk-!-margin-top-3 ${purposeError ? 'govuk-form-group--error' : ''}">
        <fieldset class="govuk-fieldset" ${purposeError ? 'aria-describedby="internal-market-purpose-error"' : ''}>
          <legend class="govuk-fieldset__legend govuk-fieldset__legend--s">
            Purpose in the internal market
          </legend>
          ${purposeError ? `<p id="internal-market-purpose-error" class="govuk-error-message"><span class="govuk-visually-hidden">Error:</span> ${escapeHtml(purposeError)}</p>` : ''}
          <div class="govuk-radios govuk-radios--small" data-module="govuk-radios">
            ${purposeItems.map((item, i) => `
              <div class="govuk-radios__item">
                <input class="govuk-radios__input" id="internal-market-purpose-${i}" name="internalMarketPurpose" type="radio" value="${escapeHtml(item.value)}" ${item.checked ? 'checked' : ''}>
                <label class="govuk-label govuk-radios__label" for="internal-market-purpose-${i}">${escapeHtml(item.text)}</label>
                ${item.hint ? `<div class="govuk-hint govuk-radios__hint">${escapeHtml(item.hint.text)}</div>` : ''}
              </div>
            `).join('')}
          </div>
        </fieldset>
      </div>
    `

    const importReasonItems = [
      {
        value: 'internal-market',
        text: 'Internal market',
        hint: { text: 'The consignment is intended for sale or use in Great Britain (England, Scotland or Wales).' },
        conditional: { html: purposeConditionalHtml }
      },
      {
        value: 're-entry',
        text: 'Re-entry',
        hint: { text: 'The consignment is authorised for re-entry or includes rejected exports that are re-entering Great Britain.' }
      }
    ]
    if (showTemporaryAdmissionHorses) {
      importReasonItems.push({
        value: 'temporary-admission-horses',
        text: 'Temporary admission horses',
        hint: { text: 'For horses authorised for temporary entry.' }
      })
    }

    res.render('v1-baseline/create/import-reason', {
      importReasonItems
    })
  })

  router.post(`${BASE}/create/import-reason`, (req, res) => {
    const importReason = req.session.data.importReason
    const internalMarketPurpose = req.session.data.internalMarketPurpose
    const commoditySpecies = req.session.data.commoditySpecies || []
    const horseSpecies = require('../../data/commodity-list.js').horseSpecies
    const showTemporaryAdmissionHorses = commoditySpecies.some(s => horseSpecies.includes(s))
    const errors = {}
    const errorList = []

    if (!importReason || importReason.trim() === '') {
      errors.importReason = 'Select the main reason for importing the animals'
      errorList.push({ href: '#import-reason-1', text: 'Select the main reason for importing the animals' })
    } else if (importReason === 'temporary-admission-horses' && !showTemporaryAdmissionHorses) {
      errors.importReason = 'Temporary admission horses is only available when importing horses'
      errorList.push({ href: '#import-reason-1', text: 'Select a valid reason for importing the animals' })
    } else if (importReason === 'internal-market' && (!internalMarketPurpose || internalMarketPurpose.trim() === '')) {
      errors.internalMarketPurpose = 'Select the purpose in the internal market'
      errorList.push({ href: '#internal-market-purpose-0', text: 'Select the purpose in the internal market' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/import-reason`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity-quantities`)
  })

  router.get(`${BASE}/create/import-reason-prefill`, (req, res) => {
    req.session.data.importReason = 'internal-market'
    req.session.data.internalMarketPurpose = 'breeding'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/commodity-quantities`)
  })

  router.get(`${BASE}/create/commodity-quantities`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commodityType = req.session.data.commodityType || 'domestic'
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const typeLabel = commodityType === 'game' ? 'Game' : 'Domestic'
    const speciesRows = commoditySpecies.map(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      return {
        key,
        speciesAndType: `${s}, ${typeLabel}`,
        quantityKey: `quantity_${key}`,
        packagesKey: `packages_${key}`
      }
    })

    let totalAnimals = 0
    let totalPackages = 0
    speciesRows.forEach(s => {
      const qty = parseInt(req.session.data[s.quantityKey], 10)
      const pkg = parseInt(req.session.data[s.packagesKey], 10)
      totalAnimals += (isNaN(qty) ? 0 : qty)
      totalPackages += (isNaN(pkg) ? 0 : pkg)
    })

    res.render('v1-baseline/create/commodity-quantities', {
      commodityDetails,
      speciesRows,
      totalAnimals,
      totalPackages
    })
  })

  router.post(`${BASE}/create/commodity-quantities`, (req, res) => {
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null
    const errors = {}
    const errorList = []

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const typeLabel = req.session.data.commodityType === 'game' ? 'Game' : 'Domestic'
    const speciesRows = commoditySpecies.map(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      return {
        key,
        speciesAndType: `${s}, ${typeLabel}`,
        quantityKey: `quantity_${key}`,
        packagesKey: `packages_${key}`
      }
    })

    speciesRows.forEach((s, i) => {
      const qtyVal = req.session.data[s.quantityKey]
      if (!qtyVal || String(qtyVal).trim() === '' || parseInt(qtyVal, 10) < 0) {
        errors[s.quantityKey] = 'Enter the number of animals'
        errorList.push({ href: `#quantity-${s.key}`, text: `Enter the number of animals for ${s.speciesAndType}` })
      }
      const pkgVal = req.session.data[s.packagesKey]
      if (pkgVal === undefined || pkgVal === null || String(pkgVal).trim() === '' || parseInt(pkgVal, 10) < 0) {
        errors[s.packagesKey] = 'Enter the number of packages'
        errorList.push({ href: `#packages-${s.key}`, text: `Enter the number of packages for ${s.speciesAndType}` })
      }
    })

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/commodity-quantities`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/animal-identification`)
  })

  router.get(`${BASE}/create/commodity-quantities-prefill`, (req, res) => {
    const commoditySpecies = req.session.data.commoditySpecies || []
    commoditySpecies.forEach(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      req.session.data[`quantity_${key}`] = 2
      req.session.data[`packages_${key}`] = 1
    })
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/animal-identification-prefill`)
  })

  router.get(`${BASE}/create/animal-identification`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commodityType = req.session.data.commodityType || 'domestic'
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const quantityKey = (s) => `quantity_${s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')}`
    const hasQuantities = commoditySpecies.some(s => {
      const q = parseInt(req.session.data[quantityKey(s)], 10)
      return !isNaN(q) && q > 0
    })
    if (!hasQuantities) {
      return res.redirect(`${BASE}/create/commodity-quantities`)
    }

    const typeLabel = commodityType === 'game' ? 'Game' : 'Domestic'
    const speciesRows = commoditySpecies.map(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      const quantityKey = `quantity_${key}`
      const quantity = parseInt(req.session.data[quantityKey], 10) || 0
      const animals = []
      for (let i = 1; i <= quantity; i++) {
        animals.push({
          index: i,
          earTagKey: `earTag_${key}_${i}`,
          passportKey: `passport_${key}_${i}`
        })
      }
      return {
        key,
        speciesAndType: `${s}, ${typeLabel}`,
        quantity,
        animals
      }
    })

    res.render('v1-baseline/create/animal-identification', {
      commodityDetails,
      speciesRows
    })
  })

  router.get(`${BASE}/create/animal-identification-prefill`, (req, res) => {
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commodityType = req.session.data.commodityType || 'domestic'
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const quantityKey = (s) => `quantity_${s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')}`
    const hasQuantities = commoditySpecies.some(s => {
      const q = parseInt(req.session.data[quantityKey(s)], 10)
      return !isNaN(q) && q > 0
    })
    if (!hasQuantities) {
      return res.redirect(`${BASE}/create/commodity-quantities`)
    }

    // BCMS (Cattle Tracing System) format: 12-digit ear tag (6 herd + 6 individual), passport UK herd check sequential
    const HERD_MARK = '123456'
    const CHECK_DIGIT = '7'
    let animalCounter = 0
    const isCattle = commodity === 'Cow'
    commoditySpecies.forEach(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      const quantityKey = `quantity_${key}`
      const quantity = parseInt(req.session.data[quantityKey], 10) || 0
      for (let i = 1; i <= quantity; i++) {
        animalCounter++
        if (isCattle) {
          req.session.data[`earTag_${key}_${i}`] = `${HERD_MARK}${String(animalCounter).padStart(6, '0')}`
          req.session.data[`passport_${key}_${i}`] = `UK ${HERD_MARK} ${CHECK_DIGIT} ${String(animalCounter).padStart(5, '0')}`
        } else {
          req.session.data[`earTag_${key}_${i}`] = `PRE-${key}-${i}`
          req.session.data[`passport_${key}_${i}`] = `PASSPORT-${key}-${i}`
        }
      }
    })

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/additional-animal-details`)
  })

  router.get(`${BASE}/create/additional-animal-details`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const quantityKey = (s) => `quantity_${s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')}`
    const hasQuantities = commoditySpecies.some(s => {
      const q = parseInt(req.session.data[quantityKey(s)], 10)
      return !isNaN(q) && q > 0
    })
    if (!hasQuantities) {
      return res.redirect(`${BASE}/create/commodity-quantities`)
    }

    res.render('v1-baseline/create/additional-animal-details')
  })

  router.post(`${BASE}/create/additional-animal-details`, (req, res) => {
    const animalsCertifiedFor = req.session.data.animalsCertifiedFor
    const unweanedAnimals = req.session.data.unweanedAnimals
    const errors = {}
    const errorList = []

    if (!animalsCertifiedFor || animalsCertifiedFor.trim() === '') {
      errors.animalsCertifiedFor = 'Select what the animals are certified for'
      errorList.push({ href: '#animals-certified-for-1', text: 'Select what the animals are certified for' })
    }
    if (!unweanedAnimals || unweanedAnimals.trim() === '') {
      errors.unweanedAnimals = 'Select if the consignment contains unweaned animals'
      errorList.push({ href: '#unweaned-animals-1', text: 'Select if the consignment contains unweaned animals' })
    }

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/additional-animal-details`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/accompanying-documents`)
  })

  router.get(`${BASE}/create/additional-animal-details-prefill`, (req, res) => {
    req.session.data.animalsCertifiedFor = 'breeding-production'
    req.session.data.unweanedAnimals = 'no'
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/accompanying-documents`)
  })

  router.get(`${BASE}/create/accompanying-documents`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    const documentTypes = require('../../data/document-types.js')
    const documentTypeItems = [{ value: '', text: 'Select document type' }].concat(documentTypes)
    const sessionDocuments = req.session.data.documents
    let documents = (sessionDocuments && sessionDocuments.length) ? sessionDocuments : [{ type: '', reference: '', date: '' }]
    // Normalise date: convert legacy dateDay/dateMonth/dateYear to YYYY-MM-DD for input type="date"
    documents = documents.map(doc => {
      const d = doc || {}
      if (d.date) return { ...d, date: d.date }
      if (d.dateDay && d.dateMonth && d.dateYear) {
        const y = String(d.dateYear).padStart(4, '0')
        const m = String(d.dateMonth).padStart(2, '0')
        const day = String(d.dateDay).padStart(2, '0')
        return { ...d, date: `${y}-${m}-${day}` }
      }
      return { ...d, date: d.date || '' }
    })
    res.render('v1-baseline/create/accompanying-documents', {
      documentTypeItems,
      documents
    })
  })

  router.post(`${BASE}/create/accompanying-documents`, (req, res) => {
    const data = req.session.data
    const documents = []
    const errors = {}
    const errorList = []
    let i = 0
    while (data[`documentType_${i}`] !== undefined) {
      const type = data[`documentType_${i}`]
      const reference = (data[`documentReference_${i}`] || '').trim()
      const date = (data[`documentDate_${i}`] || '').trim()
      const filenamesStr = data[`documentAttachmentFilenames_${i}`] || ''
      const attachments = filenamesStr ? filenamesStr.split(',').map(s => s.trim()).filter(Boolean) : []

      if (!type || type.trim() === '') {
        errors[`documentType_${i}`] = 'Select a document type'
        errorList.push({ href: `#document-type-${i}`, text: `Document ${i + 1}: Select a document type` })
      }
      if (reference === '') {
        errors[`documentReference_${i}`] = 'Enter the document reference'
        errorList.push({ href: `#document-reference-${i}`, text: `Document ${i + 1}: Enter the document reference` })
      }
      if (date === '') {
        errors[`documentDate_${i}`] = 'Enter the date of issue'
        errorList.push({ href: `#document-date-${i}`, text: `Document ${i + 1}: Enter the date of issue` })
      }

      documents.push({
        type: type || '',
        reference: reference,
        date: date,
        attachments
      })
      i++
    }
    if (documents.length === 0) {
      documents.push({ type: '', reference: '', date: '', attachments: [] })
    }
    data.documents = documents

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/accompanying-documents`)
    }

    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/addresses`)
  })

  router.get(`${BASE}/create/addresses`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList

    // Store selected consignor when coming from address-consignor-search
    const consignorId = req.query.consignor
    if (req.query.removeConsignor === '1') {
      delete data.consignorId
      delete data.consignorName
      delete data.consignorAddress
      delete data.consignorCountry
      delete data.consignor
    } else if (consignorId) {
      const consignors = require('../../data/consignors.js')
      const selected = consignors.find(c => String(c.id) === String(consignorId))
      if (selected) {
        data.consignorId = selected.id
        data.consignorName = selected.name
        data.consignorAddress = selected.address
        data.consignorCountry = selected.country
        data.consignor = selected
      }
    }

    // Handle remove consignee
    if (req.query.removeConsignee === '1') {
      delete data.consigneeName
      delete data.consigneeAddressLine1
      delete data.consigneeAddressLine2
      delete data.consigneeTown
      delete data.consigneePostcode
    }

    // Pass consignor explicitly (session may not persist nested objects reliably)
    const selected = data.consignor || (data.consignorName && { name: data.consignorName, address: data.consignorAddress, country: data.consignorCountry })
    const consignorName = (selected && selected.name) || data.consignorName || ''
    const consignorAddress = (selected && selected.address) || data.consignorAddress || ''
    const consignorCountry = (selected && selected.country) || data.consignorCountry || ''
    const hasConsignor = !!(selected || data.consignorId)

    // Consignee (UK address) – build display string
    const hasConsignee = !!(data.consigneeName && data.consigneeAddressLine1 && data.consigneeTown && data.consigneePostcode)
    const consigneeAddressLines = []
    if (data.consigneeName) consigneeAddressLines.push(data.consigneeName)
    if (data.consigneeAddressLine1) consigneeAddressLines.push(data.consigneeAddressLine1)
    if (data.consigneeAddressLine2) consigneeAddressLines.push(data.consigneeAddressLine2)
    if (data.consigneeTown) consigneeAddressLines.push(data.consigneeTown)
    if (data.consigneePostcode) consigneeAddressLines.push(data.consigneePostcode + ' United Kingdom')

    res.render('v1-baseline/create/addresses', {
      consignorName,
      consignorAddress,
      consignorCountry,
      hasConsignor,
      hasConsignee,
      consigneeAddressLines
    })
  })

  router.post(`${BASE}/create/addresses`, (req, res) => {
    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/dashboard`)
  })

  router.get(`${BASE}/create/address-consignee`, (req, res) => {
    const data = req.session.data || {}
    delete data.errors
    delete data.errorList
    res.render('v1-baseline/create/address-consignee')
  })

  router.post(`${BASE}/create/address-consignee`, (req, res) => {
    const data = req.session.data || {}
    const consigneeName = (data.consigneeName || '').trim()
    const consigneeAddressLine1 = (data.consigneeAddressLine1 || '').trim()
    const consigneeTown = (data.consigneeTown || '').trim()
    const consigneePostcode = (data.consigneePostcode || '').trim()

    const errors = {}
    const errorList = []
    if (!consigneeName) {
      errors.consigneeName = 'Enter the name or organisation'
      errorList.push({ href: '#consigneeName', text: 'Enter the name or organisation' })
    }
    if (!consigneeAddressLine1) {
      errors.consigneeAddressLine1 = 'Enter address line 1'
      errorList.push({ href: '#consigneeAddressLine1', text: 'Enter address line 1' })
    }
    if (!consigneeTown) {
      errors.consigneeTown = 'Enter the town or city'
      errorList.push({ href: '#consigneeTown', text: 'Enter the town or city' })
    }
    if (!consigneePostcode) {
      errors.consigneePostcode = 'Enter the postcode'
      errorList.push({ href: '#consigneePostcode', text: 'Enter the postcode' })
    }

    if (errorList.length > 0) {
      data.errors = errors
      data.errorList = errorList
      return res.redirect(`${BASE}/create/address-consignee`)
    }

    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/addresses`)
  })

  router.get(`${BASE}/create/address-consignor-search`, (req, res) => {
    const data = req.session.data || {}
    const consignors = require('../../data/consignors.js')
    const euCountries = require('../../data/eu-countries.js')
    const searchName = (req.query.searchName || data.searchName || '').trim().toLowerCase()
    const searchAddress = (req.query.searchAddress || data.searchAddress || '').trim().toLowerCase()
    const searchCountry = (req.query.searchCountry || data.searchCountry || '').trim()
    const page = parseInt(req.query.page, 10) || 1
    const perPage = 10

    data.searchName = req.query.searchName ?? data.searchName
    data.searchAddress = req.query.searchAddress ?? data.searchAddress
    data.searchCountry = req.query.searchCountry ?? data.searchCountry

    let filtered = consignors
    if (searchName) {
      filtered = filtered.filter(c => c.name.toLowerCase().includes(searchName))
    }
    if (searchAddress) {
      filtered = filtered.filter(c => c.address.toLowerCase().includes(searchAddress))
    }
    if (searchCountry) {
      filtered = filtered.filter(c => c.country === searchCountry)
    }

    const total = filtered.length
    const totalPages = Math.max(1, Math.ceil(total / perPage))
    const pageNum = Math.max(1, Math.min(page, totalPages))
    const start = (pageNum - 1) * perPage
    const results = filtered.slice(start, start + perPage)

    const countriesFromData = [...new Set(consignors.map(c => c.country))]
    const countries = [...new Set([...euCountries, ...countriesFromData])].sort()

    res.render('v1-baseline/create/address-consignor-search', {
      results,
      countries,
      page: pageNum,
      totalPages,
      total
    })
  })

  router.get(`${BASE}/create/accompanying-documents-prefill`, (req, res) => {
    const data = req.session.data
    data.documents = [{
      type: 'veterinary-health-certificate',
      reference: 'CHED-PP-2024-001',
      date: '2024-03-15',
      attachments: ['Sample health certificate.pdf']
    }]
    delete data.errors
    delete data.errorList
    res.redirect(`${BASE}/create/addresses`)
  })

  router.post(`${BASE}/create/animal-identification`, (req, res) => {
    const commodity = req.session.data.commodity
    const commoditySpecies = req.session.data.commoditySpecies || []
    const commoditiesData = require('../../data/commodities.js')
    const commodityDetails = commodity ? commoditiesData[commodity] : null

    if (!commodityDetails || commoditySpecies.length === 0) {
      return res.redirect(`${BASE}/create/commodity-species`)
    }

    const commodityType = req.session.data.commodityType || 'domestic'
    const typeLabel = commodityType === 'game' ? 'Game' : 'Domestic'
    const speciesRows = commoditySpecies.map(s => {
      const key = s.replace(/\s+/g, '_').toLowerCase().replace(/[^a-z0-9_]/g, '')
      const quantityKey = `quantity_${key}`
      const quantity = parseInt(req.session.data[quantityKey], 10) || 0
      const animals = []
      for (let i = 1; i <= quantity; i++) {
        animals.push({
          index: i,
          earTagKey: `earTag_${key}_${i}`,
          passportKey: `passport_${key}_${i}`
        })
      }
      return {
        key,
        speciesAndType: `${s}, ${typeLabel}`,
        quantity,
        animals
      }
    })

    const errors = {}
    const errorList = []
    speciesRows.forEach(s => {
      s.animals.forEach(a => {
        const earTagVal = req.session.data[a.earTagKey]
        const passportVal = req.session.data[a.passportKey]
        const earTagMissing = !earTagVal || String(earTagVal).trim() === ''
        const passportMissing = !passportVal || String(passportVal).trim() === ''

        if (earTagMissing) errors[a.earTagKey] = 'Enter the ear tag number'
        if (passportMissing) errors[a.passportKey] = 'Enter the passport number'

        if (earTagMissing || passportMissing) {
          const animalLabel = `${s.speciesAndType} animal ${a.index}`
          const missingParts = []
          if (earTagMissing) missingParts.push('ear tag')
          if (passportMissing) missingParts.push('passport')
          const message = missingParts.length === 2
            ? `Enter the ear tag and passport for ${animalLabel}`
            : `Enter the ${missingParts[0]} for ${animalLabel}`
          errorList.push({ href: `#ear-tag-${a.earTagKey}`, text: message })
        }
      })
    })

    if (Object.keys(errors).length > 0) {
      req.session.data.errors = errors
      req.session.data.errorList = errorList
      return res.redirect(`${BASE}/create/animal-identification`)
    }

    delete req.session.data.errors
    delete req.session.data.errorList
    res.redirect(`${BASE}/create/additional-animal-details`)
  })

  router.get(`${BASE}/clear-filters`, (req, res) => {
    FILTER_KEYS.forEach(key => delete req.session.data[key])
    res.redirect(`${BASE}/dashboard`)
  })
}
