//
// v1-baseline routes
// Generated by Cursor
//

const BASE = '/v1-baseline'

module.exports = (router) => {
  router.get(`${BASE}/start`, (req, res) => {
    res.render('v1-baseline/start')
  })
}
